/*
 * Style Dictionary build config — memory.wiki design system.
 *
 * Source of truth: design-tokens/{core,theme-dark,theme-light}/*.json
 * (DTCG-format).
 *
 * Run: `npm run tokens:build` (root package.json).
 *
 * Brand spec: https://memory.wiki/L2SHNVir
 *
 * Decision log:
 *   2026-05-31: --accent flipped from lime (#B5FF1A) to neutral
 *               (text-primary). v8 reads as pure ink + zinc.
 *               Lime stays reachable as --micro-lime for
 *               status/badge use, never as default accent.
 */

import StyleDictionary from "style-dictionary";
import { readFileSync, writeFileSync } from "fs";

// Emit semantic tokens only (core primitives are internal — apps
// always reach for the semantic name). Strip the "semantic" prefix
// so consumers see `--accent`, not `--semantic-accent`. The web
// `globals.css` and native `Brand.*` helpers already use bare
// names; this matches that contract.
function tokenName(token) {
  const path = token.path[0] === "semantic" ? token.path.slice(1) : token.path;
  return path.join("-");
}

function isSemantic(token) {
  return token.path[0] === "semantic";
}

function hexFromValue(value) {
  if (typeof value !== "string") return null;
  if (value.startsWith("#")) return value.slice(1).toUpperCase();
  // rgba(...) — preserve as-is upstream; native emitters drop
  // these with a `// rgba: <value>` comment instead of trying to
  // parse. Each platform expresses translucency differently.
  return null;
}

// CSS format: emits `--name: value;` for every semantic token,
// wrapped in the right scope selector for the theme being built.
function makeCssFormat({ selector, theme }) {
  return ({ dictionary }) => {
    const lines = dictionary.allTokens
      .filter(isSemantic)
      .map((t) => `  --${tokenName(t)}: ${t.$value ?? t.value};`);
    const header = `/* Generated by Style Dictionary. Edit design-tokens/ — never this file. THEME: ${theme.toUpperCase()}. */`;
    return `${header}\n${selector} {\n${lines.join("\n")}\n}\n`;
  };
}

const iosFormat = ({ dictionary }) => {
  const lines = dictionary.allTokens
    .filter(isSemantic)
    .map((t) => {
      const name = camelCase(tokenName(t));
      const hex = hexFromValue(t.$value ?? t.value);
      if (!hex) return `    // ${name}: rgba/literal: ${t.$value ?? t.value}`;
      return `    static let ${name} = Color(hex: 0x${hex})`;
    });
  return `// Generated by Style Dictionary. Edit design-tokens/ — never this file.\n\nimport SwiftUI\n\nenum BrandTokens {\n${lines.join("\n")}\n}\n`;
};

const androidFormat = ({ dictionary }) => {
  const lines = dictionary.allTokens
    .filter(isSemantic)
    .map((t) => {
      const name = pascalCase(tokenName(t));
      const hex = hexFromValue(t.$value ?? t.value);
      if (!hex) return `    // ${name}: rgba/literal: ${t.$value ?? t.value}`;
      const argb = hex.length === 6 ? `FF${hex}` : hex;
      return `    val ${name} = Color(0x${argb}u.toInt())`;
    });
  return `// Generated by Style Dictionary. Edit design-tokens/ — never this file.\n\npackage wiki.memory.memorywiki.ui.theme\n\nimport androidx.compose.ui.graphics.Color\n\nobject BrandTokens {\n${lines.join("\n")}\n}\n`;
};

function camelCase(s) {
  return s.split(/[-_]/).map((p, i) => (i === 0 ? p : capitalize(p))).join("");
}
function pascalCase(s) {
  return s.split(/[-_]/).map(capitalize).join("");
}
function capitalize(s) {
  return s.length === 0 ? s : s[0].toUpperCase() + s.slice(1);
}

// ─────────────────────────────────────────────────────────────
// CSS builds — one per theme, six output files (web/vscode/desktop × dark/light).
// ─────────────────────────────────────────────────────────────

async function buildCssForTheme(theme) {
  const sd = new StyleDictionary({
    source: [
      "design-tokens/core/**/*.json",
      `design-tokens/theme-${theme}/**/*.json`,
    ],
    hooks: {
      formats: {
        "css/scoped": makeCssFormat({
          selector: theme === "dark" ? `:root,\n[data-theme="dark"]` : `[data-theme="light"]`,
          theme,
        }),
      },
    },
    // No transform groups — we don't want the default color
    // transform that converts hex to UIColor literals or HSL.
    // Our format reads the raw $value. Style Dictionary's
    // built-in attribute/cti runs by default to populate token
    // paths, which is enough.
    platforms: {
      [`web-${theme}`]: {
        buildPath: "apps/web/src/app/",
        files: [{ destination: `_tokens.${theme}.generated.css`, format: "css/scoped" }],
      },
      [`vscode-${theme}`]: {
        buildPath: "apps/vscode-extension/media/",
        files: [{ destination: `_tokens.${theme}.generated.css`, format: "css/scoped" }],
      },
      [`desktop-${theme}`]: {
        buildPath: "apps/desktop/renderer/",
        files: [{ destination: `_tokens.${theme}.generated.css`, format: "css/scoped" }],
      },
    },
  });
  await sd.buildAllPlatforms();
}

// ─────────────────────────────────────────────────────────────
// Native builds — iOS + Android use the dark theme only for now.
// ─────────────────────────────────────────────────────────────

async function buildNative() {
  const sd = new StyleDictionary({
    source: [
      "design-tokens/core/**/*.json",
      "design-tokens/theme-dark/**/*.json",
    ],
    hooks: {
      formats: {
        "ios/brand-tokens-swift": iosFormat,
        "android/brand-tokens-kt": androidFormat,
      },
    },
    platforms: {
      ios: {
        buildPath: "apps/ios-native/MemoryWiki/",
        files: [{ destination: "BrandTokens.generated.swift", format: "ios/brand-tokens-swift" }],
      },
      android: {
        buildPath: "apps/android-native/app/src/main/kotlin/wiki/memory/memorywiki/ui/theme/",
        files: [{ destination: "BrandTokens.generated.kt", format: "android/brand-tokens-kt" }],
      },
    },
  });
  await sd.buildAllPlatforms();
}

// ─────────────────────────────────────────────────────────────
// Accent palette — user-selectable picker colours.
//
// Style Dictionary's main pipeline is built for THEMED tokens
// (one value per theme). The accent palette is a different shape:
// a flat list of N items, each with its own (dark, light) pair,
// label, and picker-group metadata. Treating it as DTCG semantic
// tokens would scatter each accent across two theme files and
// lose the metadata, so we read the JSON directly and emit the
// three consumers (CSS, TS, Kotlin) by hand. The contract: edit
// design-tokens/accent-palette.json; never edit the generated
// files. ACCENT_KEYS whitelist in the server PATCH route imports
// from the generated TS, so server validation auto-tracks.
// ─────────────────────────────────────────────────────────────

function hexToRgb(hex) {
  const h = hex.replace("#", "");
  return {
    r: parseInt(h.slice(0, 2), 16),
    g: parseInt(h.slice(2, 4), 16),
    b: parseInt(h.slice(4, 6), 16),
  };
}
function rgba(hex, alpha) {
  const { r, g, b } = hexToRgb(hex);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

function emitAccentCss(items) {
  const blocks = items.map((it) => {
    // Vivid uses 0.03 surface-hover on dark; gray + muted bump to
    // 0.04 because desaturated colours need slightly more lift to
    // be perceptible at hover. Light uses 0.04 across the board.
    const darkHoverAlpha = it.group === "vivid" && it.key !== "gray" ? 0.03 : 0.04;
    return [
      `/* ${it.label} */`,
      `[data-accent="${it.key}"] { --accent: ${it.dark}; --accent-dim: ${rgba(it.dark, 0.15)}; --surface-hover: ${rgba(it.dark, darkHoverAlpha)}; --badge-bg: ${rgba(it.dark, 0.15)}; }`,
      `[data-accent="${it.key}"][data-theme="light"] { --accent: ${it.light}; --accent-dim: ${rgba(it.light, 0.10)}; --surface-hover: ${rgba(it.light, 0.04)}; --badge-bg: ${rgba(it.light, 0.10)}; }`,
    ].join("\n");
  });
  const header = `/* Generated by style-dictionary.config.mjs from design-tokens/accent-palette.json. Edit the JSON; never this file. */`;
  return `${header}\n\n${blocks.join("\n\n")}\n`;
}

function emitAccentTs(items) {
  const typeUnion = items.map((it) => `  | "${it.key}"`).join("\n");
  const rows = items.map((it) => `  { name: "${it.key}", label: "${it.label}", dark: "${it.dark}", light: "${it.light}", group: "${it.group}" },`).join("\n");
  const keysArr = items.map((it) => `"${it.key}"`).join(", ");
  return `// Generated by style-dictionary.config.mjs from design-tokens/accent-palette.json. Edit the JSON; never this file.

export type AccentColor =
${typeUnion};

export type AccentGroup = "vivid" | "muted";

export interface AccentColorOption {
  name: AccentColor;
  label: string;
  /** Color used when the doc/app is in dark mode. */
  dark: string;
  /** Color used when the doc/app is in light mode. */
  light: string;
  /** Picker group. Pickers render \`vivid\` first, then \`muted\` under a section header. */
  group: AccentGroup;
}

export const ACCENT_COLORS: AccentColorOption[] = [
${rows}
];

/** Whitelist of every accent key any client can persist. The server
 *  PATCH /api/user/profile handler uses this to validate the
 *  accent_color field — native clients (iOS/Android/Desktop/VSCode/
 *  CLI) hit that endpoint over bearer auth, so anything not in this
 *  set 400s and the client's runCatching silently swallows. Keeping
 *  it derived from ACCENT_COLORS guarantees: add an item to the
 *  JSON, the server accepts it on the next build. */
export const ACCENT_KEYS: ReadonlySet<string> = new Set<string>([${keysArr}]);
`;
}

function emitAccentKotlin(items) {
  // Android picker omits the web-only vivid colours (green/teal/
  // red/yellow) to keep the row visually manageable on mobile.
  // The JSON flags them with note: "web only" — we strip those
  // from the Android enum. If a user picks one of them on web,
  // AccentColorChoice.from(...) below falls back to Gray.
  const androidItems = items.filter((it) => !(typeof it.note === "string" && it.note.includes("web only")));
  const entries = androidItems.map((it, i) => {
    const argbDark = "FF" + it.dark.replace("#", "").toUpperCase();
    const argbLight = "FF" + it.light.replace("#", "").toUpperCase();
    const groupCap = it.group === "vivid" ? "Vivid" : "Muted";
    const enumName = it.label.replace(/[^A-Za-z0-9]/g, ""); // "Lime", "Sage", etc.
    const trail = i === androidItems.length - 1 ? ";" : ",";
    return `    ${enumName}("${it.key}", Color(0x${argbDark}u.toInt()), Color(0x${argbLight}u.toInt()), AccentGroup.${groupCap})${trail}`;
  }).join("\n");
  return `// Generated by style-dictionary.config.mjs from design-tokens/accent-palette.json. Edit the JSON; never this file.

package wiki.memory.memorywiki.ui.theme

import androidx.compose.ui.graphics.Color

/** Picker group. Pickers render Vivid first, then Muted under a section header. */
enum class AccentGroup { Vivid, Muted }

/** User-selectable accent palette. Mirrors apps/web/src/lib/_accent.generated.ts
 *  minus the web-only entries (green/teal/red/yellow). */
enum class AccentColorChoice(
    val key: String,
    val dark: Color,
    val light: Color,
    val group: AccentGroup,
) {
${entries}

    companion object {
        /** Default = Gray (neutral) per v8 brand decision 2026-05-31.
         *  Lime stays in the picker as an opt-in choice. */
        fun from(key: String?): AccentColorChoice =
            entries.firstOrNull { it.key.equals(key, ignoreCase = true) } ?: Gray
    }
}
`;
}

async function buildAccentPalette() {
  const data = JSON.parse(readFileSync("design-tokens/accent-palette.json", "utf-8"));
  const items = data.items;
  const css = emitAccentCss(items);
  writeFileSync("apps/web/src/app/_accent.generated.css", css, "utf-8");
  // VS Code + Desktop webviews consume the same accent rules so a
  // single edit to design-tokens/accent-palette.json propagates to
  // every surface, not just web. Without this mirror the sidebar
  // and preview panes stayed on hand-typed hex literals and drifted
  // (founder report: "라임이 키컬러로 쓰이고 있음" — lime hard-coded
  // in sidebar.ts even though the SOT was already neutral).
  writeFileSync("apps/vscode-extension/media/_accent.generated.css", css, "utf-8");
  writeFileSync("apps/desktop/renderer/_accent.generated.css", css, "utf-8");
  writeFileSync("apps/web/src/lib/_accent.generated.ts", emitAccentTs(items), "utf-8");
  writeFileSync(
    "apps/android-native/app/src/main/kotlin/wiki/memory/memorywiki/ui/theme/_AccentCatalog.generated.kt",
    emitAccentKotlin(items),
    "utf-8",
  );
}

async function run() {
  await buildCssForTheme("dark");
  await buildCssForTheme("light");
  await buildNative();
  await buildAccentPalette();
  console.log("design-tokens emit OK");
}

run().catch((err) => {
  console.error("design-tokens emit FAILED:", err);
  process.exitCode = 1;
});
