/*
 * Style Dictionary build config — memory.wiki design system.
 *
 * Source of truth: design-tokens/{core,theme-dark,theme-light}/*.json
 * (DTCG-format).
 *
 * Run: `npm run tokens:build` (root package.json).
 *
 * Brand spec: https://memory.wiki/L2SHNVir
 *
 * Decision log:
 *   2026-05-31: --accent flipped from lime (#B5FF1A) to neutral
 *               (text-primary). v8 reads as pure ink + zinc.
 *               Lime stays reachable as --micro-lime for
 *               status/badge use, never as default accent.
 */

import StyleDictionary from "style-dictionary";

// Emit semantic tokens only (core primitives are internal — apps
// always reach for the semantic name). Strip the "semantic" prefix
// so consumers see `--accent`, not `--semantic-accent`. The web
// `globals.css` and native `Brand.*` helpers already use bare
// names; this matches that contract.
function tokenName(token) {
  const path = token.path[0] === "semantic" ? token.path.slice(1) : token.path;
  return path.join("-");
}

function isSemantic(token) {
  return token.path[0] === "semantic";
}

function hexFromValue(value) {
  if (typeof value !== "string") return null;
  if (value.startsWith("#")) return value.slice(1).toUpperCase();
  // rgba(...) — preserve as-is upstream; native emitters drop
  // these with a `// rgba: <value>` comment instead of trying to
  // parse. Each platform expresses translucency differently.
  return null;
}

// CSS format: emits `--name: value;` for every semantic token,
// wrapped in the right scope selector for the theme being built.
function makeCssFormat({ selector, theme }) {
  return ({ dictionary }) => {
    const lines = dictionary.allTokens
      .filter(isSemantic)
      .map((t) => `  --${tokenName(t)}: ${t.$value ?? t.value};`);
    const header = `/* Generated by Style Dictionary. Edit design-tokens/ — never this file. THEME: ${theme.toUpperCase()}. */`;
    return `${header}\n${selector} {\n${lines.join("\n")}\n}\n`;
  };
}

const iosFormat = ({ dictionary }) => {
  const lines = dictionary.allTokens
    .filter(isSemantic)
    .map((t) => {
      const name = camelCase(tokenName(t));
      const hex = hexFromValue(t.$value ?? t.value);
      if (!hex) return `    // ${name}: rgba/literal: ${t.$value ?? t.value}`;
      return `    static let ${name} = Color(hex: 0x${hex})`;
    });
  return `// Generated by Style Dictionary. Edit design-tokens/ — never this file.\n\nimport SwiftUI\n\nenum BrandTokens {\n${lines.join("\n")}\n}\n`;
};

const androidFormat = ({ dictionary }) => {
  const lines = dictionary.allTokens
    .filter(isSemantic)
    .map((t) => {
      const name = pascalCase(tokenName(t));
      const hex = hexFromValue(t.$value ?? t.value);
      if (!hex) return `    // ${name}: rgba/literal: ${t.$value ?? t.value}`;
      const argb = hex.length === 6 ? `FF${hex}` : hex;
      return `    val ${name} = Color(0x${argb}u.toInt())`;
    });
  return `// Generated by Style Dictionary. Edit design-tokens/ — never this file.\n\npackage wiki.memory.memorywiki.ui.theme\n\nimport androidx.compose.ui.graphics.Color\n\nobject BrandTokens {\n${lines.join("\n")}\n}\n`;
};

function camelCase(s) {
  return s.split(/[-_]/).map((p, i) => (i === 0 ? p : capitalize(p))).join("");
}
function pascalCase(s) {
  return s.split(/[-_]/).map(capitalize).join("");
}
function capitalize(s) {
  return s.length === 0 ? s : s[0].toUpperCase() + s.slice(1);
}

// ─────────────────────────────────────────────────────────────
// CSS builds — one per theme, six output files (web/vscode/desktop × dark/light).
// ─────────────────────────────────────────────────────────────

async function buildCssForTheme(theme) {
  const sd = new StyleDictionary({
    source: [
      "design-tokens/core/**/*.json",
      `design-tokens/theme-${theme}/**/*.json`,
    ],
    hooks: {
      formats: {
        "css/scoped": makeCssFormat({
          selector: theme === "dark" ? `:root,\n[data-theme="dark"]` : `[data-theme="light"]`,
          theme,
        }),
      },
    },
    // No transform groups — we don't want the default color
    // transform that converts hex to UIColor literals or HSL.
    // Our format reads the raw $value. Style Dictionary's
    // built-in attribute/cti runs by default to populate token
    // paths, which is enough.
    platforms: {
      [`web-${theme}`]: {
        buildPath: "apps/web/src/app/",
        files: [{ destination: `_tokens.${theme}.generated.css`, format: "css/scoped" }],
      },
      [`vscode-${theme}`]: {
        buildPath: "apps/vscode-extension/media/",
        files: [{ destination: `_tokens.${theme}.generated.css`, format: "css/scoped" }],
      },
      [`desktop-${theme}`]: {
        buildPath: "apps/desktop/renderer/",
        files: [{ destination: `_tokens.${theme}.generated.css`, format: "css/scoped" }],
      },
    },
  });
  await sd.buildAllPlatforms();
}

// ─────────────────────────────────────────────────────────────
// Native builds — iOS + Android use the dark theme only for now.
// ─────────────────────────────────────────────────────────────

async function buildNative() {
  const sd = new StyleDictionary({
    source: [
      "design-tokens/core/**/*.json",
      "design-tokens/theme-dark/**/*.json",
    ],
    hooks: {
      formats: {
        "ios/brand-tokens-swift": iosFormat,
        "android/brand-tokens-kt": androidFormat,
      },
    },
    platforms: {
      ios: {
        buildPath: "apps/ios-native/MemoryWiki/",
        files: [{ destination: "BrandTokens.generated.swift", format: "ios/brand-tokens-swift" }],
      },
      android: {
        buildPath: "apps/android-native/app/src/main/kotlin/wiki/memory/memorywiki/ui/theme/",
        files: [{ destination: "BrandTokens.generated.kt", format: "android/brand-tokens-kt" }],
      },
    },
  });
  await sd.buildAllPlatforms();
}

async function run() {
  await buildCssForTheme("dark");
  await buildCssForTheme("light");
  await buildNative();
  console.log("design-tokens emit OK");
}

run().catch((err) => {
  console.error("design-tokens emit FAILED:", err);
  process.exitCode = 1;
});
