// BrandTheme — iOS façade over the canonical design tokens.
//
// All colors below delegate to `BrandTokens` (generated by
// Style Dictionary from /design-tokens/*.json — never edit
// BrandTokens.generated.swift directly). Run
// `npm run tokens:build` at repo root after changing a token.
//
// Rules of thumb (from the v8 color-balance feedback memo):
//   - Body / chips / buttons stay INK (`Brand.textPrimary`).
//     The accent role is neutral (= text-primary); status
//     semantics live in `microLime / microInfo / microWarn /
//     microRed` and are used only for small dots, badges,
//     micro-icons.
//   - No system blue, no SF Symbol-only affordances, no rounded
//     "system" buttons. Everything renders against the brand
//     tokens below.
//
// Why a façade instead of using BrandTokens directly?
//   Two reasons. (1) Existing call sites all reach for `Brand.X`
//   so the façade keeps them compiling. (2) BrandTokens only
//   knows opaque hex; translucent variants (accentDim, borderDim,
//   toggleBg) and the secondary `canvas` shade live here as
//   compositions on top of the generated primitives.

import SwiftUI
import UIKit

enum Brand {
    // MARK: - Color tokens (delegated to BrandTokens.generated.swift)

    /// Page background — slightly lifted from pure-black.
    static let background = BrandTokens.background

    /// Even darker — used behind navigation chrome on split-pane
    /// surfaces so they read as one layer back. Not in tokens
    /// yet (only one consumer); kept local until a second use
    /// surfaces and justifies promotion.
    static let canvas     = Color(hex: 0x070708)

    /// Card / row surface.
    static let surface    = BrandTokens.surface

    /// Hairline borders + the quiet ring around inactive controls.
    static let border     = BrandTokens.border
    static let borderDim  = BrandTokens.border.opacity(0.6)

    /// Toggle hover / pressed background.
    static let toggleBg   = BrandTokens.surface.opacity(0.8)

    static let textPrimary   = BrandTokens.textPrimary
    static let textSecondary = BrandTokens.textSecondary
    static let textMuted     = BrandTokens.textMuted
    static let textFaint     = BrandTokens.textFaint

    /// v8 brand decision: no key accent color. The accent role
    /// resolves to neutral text-primary ink. Status semantics
    /// live in the micro-* family below.
    static let accent     = BrandTokens.accent
    static let accentDim  = BrandTokens.accent.opacity(0.08)

    /// Micro-color tokens. Each one signals a status, never a
    /// brand. Use sparingly — small dots, badges, status icons.
    static let microInfo  = BrandTokens.microInfo
    static let microWarn  = BrandTokens.microWarn
    static let microRed   = BrandTokens.microRed
    static let microLime  = BrandTokens.microLime

    // MARK: - Typography

    /// Cal Sans 600 — the display face for app-name and large H1.
    /// Falls back to system rounded if the bundled font fails to
    /// register (CI / non-iOS targets).
    ///
    /// `.weight(.semibold)` is layered on top so non-Latin glyphs
    /// (Korean / CJK — CalSans only covers Latin) render in the
    /// system fallback at semibold weight instead of the default
    /// regular, which made Korean H1 read as too thin against the
    /// Cal Sans letterforms next to it.
    static func display(size: CGFloat) -> Font {
        if UIFont(name: "CalSans-Regular", size: size) != nil {
            return Font.custom("CalSans-Regular", size: size).weight(.semibold)
        }
        return Font.system(size: size, weight: .semibold, design: .rounded)
    }

    /// Noto Sans — the body face. Most prose, list rows, form
    /// labels. Weights: 400 / 500 / 600.
    static func body(size: CGFloat = 15, weight: Font.Weight = .regular) -> Font {
        let suffix: String
        switch weight {
        case .semibold, .bold, .heavy, .black: suffix = "SemiBold"
        case .medium: suffix = "Medium"
        default: suffix = "Regular"
        }
        let name = "NotoSans-\(suffix)"
        if UIFont(name: name, size: size) != nil {
            return Font.custom(name, size: size)
        }
        return Font.system(size: size, weight: weight)
    }

    /// JetBrains Mono — the mono face. URL display, faint
    /// uppercase captions, numbers in lists.
    static func mono(size: CGFloat = 11, weight: Font.Weight = .regular) -> Font {
        let name = weight == .medium ? "JetBrainsMono-Medium" : "JetBrainsMono-Regular"
        if UIFont(name: name, size: size) != nil {
            return Font.custom(name, size: size)
        }
        return Font.system(size: size, weight: weight, design: .monospaced)
    }

    // MARK: - Common shapes

    /// Standard quiet button — ink text on the surface fill with a
    /// hairline border. Use for the primary CTA on each screen.
    /// Lime stays out of the button per the color-balance rule.
    struct QuietButtonStyle: ButtonStyle {
        var prominent: Bool = false
        func makeBody(configuration: Configuration) -> some View {
            configuration.label
                .font(Brand.body(size: 15, weight: .medium))
                .foregroundStyle(prominent ? Brand.background : Brand.textPrimary)
                .frame(maxWidth: .infinity)
                .padding(.vertical, 13)
                .background(
                    RoundedRectangle(cornerRadius: 10, style: .continuous)
                        .fill(prominent ? Brand.textPrimary : Brand.surface)
                )
                .overlay(
                    RoundedRectangle(cornerRadius: 10, style: .continuous)
                        .strokeBorder(prominent ? .clear : Brand.border, lineWidth: 1)
                )
                .opacity(configuration.isPressed ? 0.82 : 1)
                .animation(.snappy(duration: 0.12), value: configuration.isPressed)
        }
    }
}

// MARK: - Hex helper

extension Color {
    /// Init from an `0xRRGGBB` literal. Keeps the BrandTheme call
    /// sites compact and lets us paste hex values from the web
    /// CSS without converting.
    init(hex: UInt32, opacity: Double = 1) {
        let r = Double((hex >> 16) & 0xFF) / 255
        let g = Double((hex >> 8) & 0xFF) / 255
        let b = Double(hex & 0xFF) / 255
        self.init(.sRGB, red: r, green: g, blue: b, opacity: opacity)
    }
}

// MARK: - iOS 26 sheet chrome

extension View {
    /// Unified iOS 26 sheet treatment — drag indicator, glass
    /// presentation background, dark color scheme, and the caller-
    /// supplied detents. Every modal in the app routes through this
    /// so corner radius, material, and chrome stay consistent.
    func iOS26Sheet(_ detents: Set<PresentationDetent>) -> some View {
        self
            .presentationDetents(detents)
            .presentationDragIndicator(.visible)
            // Solid near-background dark — `.ultraThinMaterial` was
            // reading too bright/light against the dark canvas
            // (bled the parent surface through). Pure Brand.background
            // (#09090B) read too dark/flat. Mid-tone #111114 sits a
            // hair above background so the sheet edge is visible
            // against the parent without losing the ink-on-dark
            // identity.
            .presentationBackground(Color(hex: 0x111114))
            .presentationCornerRadius(28)
            .preferredColorScheme(.dark)
    }
}
