// Generated by Style Dictionary. Edit design-tokens/ — never this file.

import SwiftUI

enum BrandTokens {
    static let background = Color(hex: 0x15151A)
    static let surface = Color(hex: 0x18181B)
    // surfaceHover: rgba/literal: rgba(255, 255, 255, 0.03)
    static let sheetBg = Color(hex: 0x111114)
    static let border = Color(hex: 0x27272A)
    // borderDim: rgba/literal: rgba(39, 39, 42, 0.6)
    static let textPrimary = Color(hex: 0xFAFAFA)
    static let textSecondary = Color(hex: 0xD4D4D8)
    static let textMuted = Color(hex: 0xA1A1AA)
    static let textFaint = Color(hex: 0x8A8A91)
    static let accent = Color(hex: 0xFAFAFA)
    // accentDim: rgba/literal: rgba(255, 255, 255, 0.08)
    static let microLime = Color(hex: 0xB5FF1A)
    static let microOrange = Color(hex: 0xFF6B1A)
    static let microAi = Color(hex: 0x8B5CF6)
    static let microInfo = Color(hex: 0x60A5FA)
    static let microWarn = Color(hex: 0xFBBF24)
    static let microRed = Color(hex: 0xEF4444)
    static let microPink = Color(hex: 0xFF2A7D)
}
