"use client";

import { useState } from "react";
import { VariantNav } from "../VariantNav";
import "./light.css";

export function LightVariant() {
  const [streamedText, setStreamedText] = useState("");
  const fullText =
    "Your weekly digest: 12 captures this week, clustered into 3 themes. " +
    "Memory.Wiki noticed a strong connection between your TypeScript notes " +
    "and the new design system you started capturing on Thursday.";

  const startStream = () => {
    setStreamedText("");
    let i = 0;
    const interval = setInterval(() => {
      i++;
      setStreamedText(fullText.slice(0, i));
      if (i >= fullText.length) clearInterval(interval);
    }, 18);
  };

  return (
    <div className="v8-light">
      <VariantNav />

      <section className="hero">
        <div className="badge">v8 · Light Paper variant</div>
        <h1 className="display">
          Stop re-explaining
          <br />
          <em>your context</em> to every AI.
        </h1>
        <p className="hero-sub">
          One URL every AI fetches. Yours, your team&apos;s, or your community&apos;s.
        </p>
        <div className="cta-row">
          <button className="btn-primary">Start your Memory.Wiki</button>
          <button className="btn-ghost">See an example →</button>
        </div>
      </section>

      {/* Palette */}
      <section className="section">
        <h2 className="section-title">Paper-light palette</h2>
        <div className="palette-grid">
          <Swatch label="Paper" hex="#faf6ee" />
          <Swatch label="Surface" hex="#f3ecdd" />
          <Swatch label="Elevated" hex="#ffffff" />
          <Swatch label="Ink" hex="#2a1f15" />
          <Swatch label="Muted" hex="#6b5e4d" />
          <Swatch label="Accent" hex="#d97706" />
          <Swatch label="AI tint" hex="#b07840" />
          <Swatch label="Border" hex="#e6dbc4" />
        </div>
      </section>

      {/* Cards */}
      <section className="section">
        <h2 className="section-title">Dual-layer cards</h2>
        <p className="section-lede">
          Notebook feel · warm AI accent (no purple) · drop shadows minimal
        </p>
        <div className="card-row">
          <div className="card card-user">
            <div className="card-meta">
              <div className="avatar">R</div>
              <span className="card-author">raymind</span>
              <span className="card-time">2h ago</span>
            </div>
            <h3 className="card-title">v8 thinking — capture vs memory</h3>
            <p className="card-body">
              Memory.Wiki 이 메모리 레이어가 되려면 나에 대해서 잘 알아야 함.
              그래서 capture everything 이 자연스러운 입구.
            </p>
            <div className="card-tags">
              <span className="tag">#v8</span>
              <span className="tag">#thinking</span>
            </div>
          </div>

          <div className="card card-ai">
            <div className="card-meta">
              <span className="badge-ai">
                <span className="sparkle">✦</span> Generated by Claude
              </span>
              <span className="card-time">Sunday digest</span>
            </div>
            <h3 className="card-title">Weekly synthesis — 3 themes emerged</h3>
            <p className="card-body">
              You captured 12 docs this week across TypeScript patterns,
              v8 design direction, and cross-AI memory thinking. The strongest
              connection is between your design notes from Thursday and the
              v8 plan you wrote Monday.
            </p>
            <div className="card-tags">
              <span className="tag tag-ai">#digest</span>
              <span className="tag tag-ai">#synthesis</span>
            </div>
          </div>

          <div className="card card-user">
            <div className="card-meta">
              <div className="avatar">R</div>
              <span className="card-author">raymind</span>
              <span className="card-footnote">
                <em>edited — originally Claude</em>
              </span>
            </div>
            <h3 className="card-title">My current focus</h3>
            <p className="card-body">
              Shipping Memory.Wiki v8 over 20 weeks. Capture → Organize →
              Use framework. Cross-AI delivery is the wedge giants cannot build.
            </p>
            <div className="card-tags">
              <span className="tag">#focus</span>
              <span className="tag">#v8</span>
            </div>
          </div>
        </div>
      </section>

      {/* Streaming */}
      <section className="section">
        <h2 className="section-title">AI streaming feel</h2>
        <div className="card card-ai streaming-demo">
          <div className="card-meta">
            <span className="badge-ai">
              <span className="sparkle">✦</span> Memory.Wiki AI
            </span>
            <button className="stream-btn" onClick={startStream}>
              Generate again
            </button>
          </div>
          <p className="card-body streaming-text">
            {streamedText || (
              <span className="streaming-prompt">Click &ldquo;Generate again&rdquo; →</span>
            )}
            {streamedText && streamedText.length < fullText.length && (
              <span className="cursor" />
            )}
          </p>
        </div>
      </section>

      {/* Buttons */}
      <section className="section">
        <h2 className="section-title">Buttons</h2>
        <div className="button-row">
          <button className="btn-primary">Primary</button>
          <button className="btn-secondary">Secondary</button>
          <button className="btn-ghost">Ghost</button>
          <button className="btn-ai">
            <span className="sparkle">✦</span> AI action
          </button>
        </div>
      </section>

      {/* Logo */}
      <section className="section">
        <h2 className="section-title">Logo — Layered M on paper</h2>
        <div className="logo-row">
          <LayeredM size={48} />
          <LayeredM size={96} />
          <LayeredM size={160} />
        </div>
        <div className="logo-row">
          <div className="logo-card">
            <Wordmark />
            <span className="caption">Wordmark on paper</span>
          </div>
        </div>
      </section>

      <footer className="footer">
        <p>v8 Variant B · Light Paper · Fraunces serif + warm cream</p>
        <p className="caption">
          References: Granola, Things, Apple Notes, a Moleskine notebook.
        </p>
      </footer>
    </div>
  );
}

function Swatch({ label, hex }: { label: string; hex: string }) {
  return (
    <div className="swatch">
      <div className="swatch-tile" style={{ background: hex }} />
      <div className="swatch-meta">
        <span className="swatch-label">{label}</span>
        <span className="swatch-hex">{hex}</span>
      </div>
    </div>
  );
}

function LayeredM({ size = 64 }: { size?: number }) {
  const stroke = Math.max(2, Math.round(size * 0.16));
  return (
    <svg width={size} height={size} viewBox="0 0 100 100" style={{ display: "block" }}>
      <rect width="100" height="100" rx="22" fill="#faf6ee" />
      <path
        d="M22 76 V 32 L 50 60 L 78 32 V 76"
        fill="none"
        stroke="#b07840"
        strokeWidth={stroke}
        strokeLinejoin="round"
        strokeLinecap="round"
        transform="translate(4 4)"
        opacity="0.45"
      />
      <path
        d="M22 76 V 32 L 50 60 L 78 32 V 76"
        fill="none"
        stroke="#d97706"
        strokeWidth={stroke}
        strokeLinejoin="round"
        strokeLinecap="round"
      />
    </svg>
  );
}

function Wordmark() {
  return (
    <span
      style={{
        fontFamily: "var(--font-fraunces), serif",
        fontSize: 38,
        fontWeight: 500,
        lineHeight: 1,
        letterSpacing: "-0.02em",
      }}
    >
      <span style={{ color: "#d97706" }}>Memory</span>
      <span style={{ color: "#2a1f15" }}>.Wiki</span>
    </span>
  );
}
