-- 037: Demo account expansion.
--
-- Builds on 036_demo_account_seed.sql.template. Run 036 first so the
-- profile row + the existing 6 docs / 2 bundles exist. Then run this.
--
-- Adds:
--   * 44 documents → 50 total
--   * 7 my-section folders + 3 bundle-section folders
--   * 5 bundles → 7 total (mix of public, restricted, private)
--   * folder assignments + permission variety (public, private,
--     restricted)
--   * existing 6 docs from 036 get re-homed into their best-fit folders
--     via UPDATE statements at the bottom
--
-- This file is `.sql.template` for the same reason 036 is — it
-- contains `4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd` placeholders. Substitute before push.
--
-- HOW TO APPLY (after 036):
--   1. cp 037_demo_account_expand.sql.template 037_demo_account_expand.sql
--   2. sed -i '' 's/4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd/...uuid.../g' 037_demo_account_expand.sql
--   3. supabase db push --include-all
--
-- Generated by _demo_seed_generator.py — re-run that script to update.

-- ─── 1. Folders (my-section) ─────────────────────────────────────────
INSERT INTO folders (id, user_id, name, section, sort_order, collapsed) VALUES
  ('folder-demo-conversations', '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd', 'AI Conversations', 'my', 1, false)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, sort_order = EXCLUDED.sort_order;
INSERT INTO folders (id, user_id, name, section, sort_order, collapsed) VALUES
  ('folder-demo-decisions', '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd', 'Engineering Decisions', 'my', 2, false)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, sort_order = EXCLUDED.sort_order;
INSERT INTO folders (id, user_id, name, section, sort_order, collapsed) VALUES
  ('folder-demo-research', '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd', 'Research Notes', 'my', 3, false)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, sort_order = EXCLUDED.sort_order;
INSERT INTO folders (id, user_id, name, section, sort_order, collapsed) VALUES
  ('folder-demo-strategy', '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd', 'Strategy & GTM', 'my', 4, false)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, sort_order = EXCLUDED.sort_order;
INSERT INTO folders (id, user_id, name, section, sort_order, collapsed) VALUES
  ('folder-demo-formatting', '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd', 'Writing & Formatting', 'my', 5, false)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, sort_order = EXCLUDED.sort_order;
INSERT INTO folders (id, user_id, name, section, sort_order, collapsed) VALUES
  ('folder-demo-integrate', '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd', 'AI Tool Integration', 'my', 6, false)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, sort_order = EXCLUDED.sort_order;
INSERT INTO folders (id, user_id, name, section, sort_order, collapsed) VALUES
  ('folder-demo-private-vault', '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd', 'Private Vault', 'my', 7, false)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, sort_order = EXCLUDED.sort_order;

-- ─── 2. Folders (bundles-section) ────────────────────────────────
INSERT INTO folders (id, user_id, name, section, sort_order, collapsed) VALUES
  ('folder-demo-bundles-ai', '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd', 'AI Memory', 'bundles', 1, false)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, sort_order = EXCLUDED.sort_order;
INSERT INTO folders (id, user_id, name, section, sort_order, collapsed) VALUES
  ('folder-demo-bundles-engineering', '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd', 'Engineering', 'bundles', 2, false)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, sort_order = EXCLUDED.sort_order;
INSERT INTO folders (id, user_id, name, section, sort_order, collapsed) VALUES
  ('folder-demo-bundles-vault', '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd', 'Private Bundles', 'bundles', 3, false)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, sort_order = EXCLUDED.sort_order;

-- ─── 3. Re-home existing 036 docs into folders ─────────────────────
UPDATE documents SET folder_id = 'folder-demo-conversations' WHERE id = 'demo-ai-memory-chat' AND user_id = '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd';
UPDATE documents SET folder_id = 'folder-demo-decisions' WHERE id = 'demo-decision-graph-url' AND user_id = '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd';
UPDATE documents SET folder_id = 'folder-demo-formatting' WHERE id = 'demo-formatting-tour' AND user_id = '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd';
UPDATE documents SET folder_id = 'folder-demo-strategy' WHERE id = 'demo-strategy-moat' AND user_id = '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd';
UPDATE documents SET folder_id = 'folder-demo-integrate' WHERE id = 'demo-cursor-rules' AND user_id = '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd';
UPDATE documents SET folder_id = 'folder-demo-research' WHERE id = 'demo-karpathy-llm-wiki' AND user_id = '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd';

-- ─── 4. New documents (44) ─────────────────────────────────────────

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-conv-claude-rust-perf',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Captured chat with Claude Sonnet, 2026-04-02. Cleaned up.

## Premise

I asked Claude to walk through three places we lose Rust perf in the WASM build.

## What it said

1. **alloc on hot paths** — we leak `String::new()` in `flavor.rs`.
2. **bound-check loops** — the per-line scan in `postprocess.rs` runs without `unsafe { get_unchecked }` even where we know the bound.

## What I'm doing

Skipping (1) for now (LOC cost ↑, perf ↓ <1%). Filed (2) as an issue, will pair with the WASM rebuild PR.$MD$,
  'Claude on Rust performance pitfalls',
  'demo-tok-conv-claude-rust-per',
  false,
  'account',
  'folder-demo-conversations',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-conv-gpt5-token-budget',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> ChatGPT-5 share link → mdfy. 2026-04-09.

## Setup

I dumped the AGENTS.md proposal + 4 hub bundles.

## Output

It built a 'context budget' worksheet I genuinely use now: pre-allocate 30% to project context, 30% to recent edits, 40% to live conversation.

## Caveat

Worksheet over-fits to *coding* contexts. For research the ratios invert.$MD$,
  'GPT-5 on context-budget rituals',
  'demo-tok-conv-gpt5-token-budg',
  false,
  'account',
  'folder-demo-conversations',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-conv-gemini-image-prompt',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Gemini 2.5 Pro, after I asked it to generate Mermaid for a 3-tier auth flow.

## Insight

Gemini suggested I describe the *flow* (who calls who, what data crosses the boundary) instead of node shapes. The diagram came out tighter.

## Pattern

Always: actors → calls → data → constraints. The shapes follow.$MD$,
  'Gemini on diagram prompting',
  'demo-tok-conv-gemini-image-pr',
  false,
  'account',
  'folder-demo-conversations',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-conv-claude-onboarding',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Working session pulling the 5-slide welcome design.

## Decision

One CTA per slide. The brand badge sits above the title only on slide 1.

## Why

User testing showed people read 1.3 cards before clicking somewhere. 5 slides × multiple CTAs = 0% scroll-completion in the dogfood test.$MD$,
  'Claude pair: writing the v6 onboarding overlay',
  'demo-tok-conv-claude-onboardi',
  false,
  'account',
  'folder-demo-conversations',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-dec-postgres-vs-pinecone',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Logged 2026-03-08 after a 2-day evaluation.

## Choice

pgvector + HNSW inside the existing Supabase Postgres, NOT a managed vector DB.

## Why

Avoided a second vendor + second auth layer + second migration story. Read latency on our hub recall (200-doc index) is 18ms p99 — well inside our 100ms budget.

## Tradeoff

When we grow past ~50K docs/user we'll need to re-evaluate.$MD$,
  'Decision: Supabase pgvector over Pinecone',
  'demo-tok-dec-postgres-vs-pine',
  false,
  'account',
  'folder-demo-decisions',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-dec-rust-wasm-engine',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Recurring conversation that I've now closed.

## Choice

comrak (Rust) compiled to WASM stays the renderer. No move to remark or markdown-it.

## Why

GFM correctness + perf. Rebuilds in CI in 38s.$MD$,
  'Decision: Keep the Markdown engine in Rust + WASM',
  'demo-tok-dec-rust-wasm-engine',
  false,
  'account',
  'folder-demo-decisions',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-dec-haiku-reranker',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Documented 2026-04-11.

## Choice

Haiku 4.5 reranks the top-30 hybrid result down to top-10.

## Why

Cheaper than Voyage rerank; quality is within noise on our internal eval set. Single-vendor story for now.

## Followup

Re-eval when Voyage-rerank-2.5 drops.$MD$,
  'Decision: Anthropic Haiku for hub-recall reranker',
  'demo-tok-dec-haiku-reranker',
  false,
  'account',
  'folder-demo-decisions',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-dec-bundle-graph-inline',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Linked to demo-decision-graph-url; this is the engineering version.

## Choice

Bundle digest carries graph_data as a JSON-LD block in the markdown response.

## Why

Receiving AI gets themes/insights/relations without a second fetch. Adds ~3KB per bundle.$MD$,
  'Decision: Inline graph_data in bundle URLs',
  'demo-tok-dec-bundle-graph-inl',
  false,
  'account',
  'folder-demo-decisions',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-dec-no-wikilinks',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> See /spec for the public statement. This is the internal version.

## Choice

No [[]] syntax. We rely on AI-derived concept_index + related-in-this-hub instead.

## Why

The AI-era wiki bet is that authoring shouldn't require linking markup; the system links for you.

## Risk

Obsidian users miss it. We accept that.$MD$,
  'Decision: Drop [[wikilinks]] permanently',
  'demo-tok-dec-no-wikilinks',
  false,
  'account',
  'folder-demo-decisions',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-res-graph-rag-microsoft',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Read the 2024 paper and the follow-ups. Notes for the team.

## Approach

Builds a knowledge graph from a corpus, then runs a community-detection step. Queries traverse the graph.

## What's good

Multi-hop reasoning. Beats naive RAG on 'compare X and Y across documents.'

## Why it's not us

It's a *service*. mdfy ships the graph in the URL response. Different shape.$MD$,
  'Microsoft GraphRAG: what we learned',
  'demo-tok-res-graph-rag-micros',
  false,
  'account',
  'folder-demo-research',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-res-mem0-vs-letta',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Side-by-side after 3 weeks of usage.

## Mem0

Faster extraction. Better at facts ('user's company is X').

## Letta

Better at preferences ('user prefers shorter responses'). Looser memory boundary.

## Both

Extracted memory ≠ authored memory. mdfy is the second.$MD$,
  'Mem0 vs Letta: extracted memory comparison',
  'demo-tok-res-mem0-vs-letta',
  false,
  'account',
  'folder-demo-research',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-res-llms-txt-adoption',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> 2026-05 snapshot.

## Adopting

Vercel, Cloudflare, Anthropic docs, Resend, Trigger.dev, mdfy.

## Considering

Several DX platforms (no specific names yet).

## Pattern

Devtool companies first. Consumer-facing sites haven't moved.$MD$,
  'llms.txt adoption: who''s actually shipping it',
  'demo-tok-res-llms-txt-adoptio',
  false,
  'account',
  'folder-demo-research',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-res-karpathy-llm-wiki-expanded',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Expansion of the public summary in demo-karpathy-llm-wiki.

## Maps cleanly

Personal knowledge as the input. Wiki shape. AI as the reader.

## Doesn't map

Local-only assumption. Karpathy's spec is Obsidian-first; we're URL-first.

## Bridge

Per-project scopes (bundles) give us the AGENTS.md / .cursor/rules surface area Karpathy's local-file world doesn't reach.$MD$,
  'Karpathy wiki: the parts that map',
  'demo-tok-res-karpathy-llm-wik',
  false,
  'account',
  'folder-demo-research',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-res-context-engineering',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Trend notes, May 2026.

## Bet

'Prompt engineering' collapses into 'context engineering' over the next 12 months.

## Evidence

Cursor's project context, Claude's projects, ChatGPT's GPTs — all converging on shaped context as the primitive.

## Implication

mdfy's URL-shaped memory is the right primitive at the right time. We need to communicate it as 'context, deployable.'$MD$,
  'Context engineering: where it goes next',
  'demo-tok-res-context-engineer',
  false,
  'account',
  'folder-demo-research',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-strat-cross-ai-thesis',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> The argument distilled.

## Claim

AI companies cannot build cross-AI memory. Their incentive is to keep you in their walled garden.

## Implication

The 'layer above AI' is structurally available only to a non-AI-company.

## Risk

Someone else builds it first. Speed matters.$MD$,
  'Cross-AI as a structural moat',
  'demo-tok-strat-cross-ai-thesi',
  false,
  'account',
  'folder-demo-strategy',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-strat-pricing-model',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Internal pricing scratchpad. Restricted to the team.

## Free

Capture + hub + cross-AI deployment forever.

## Pro tier

No-badge, custom domain, analytics, auto-analyze (stale-fetch triggers background graph regen).

## Price band

$8-12/mo working range. TBD until beta closes.$MD$,
  'Pricing model thoughts',
  'demo-tok-strat-pricing-model',
  false,
  'account',
  'folder-demo-strategy',
  '{kyle@mdfy.app,demo@mdfy.app}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-strat-launch-day',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Show HN day plan.

## Top of front page for 4h

Realistic upside.

## 100 sign-ups

Reasonable mid case.

## Two follow-up posts

Build narrative continuity for week 2.$MD$,
  'Launch day: what success looks like',
  'demo-tok-strat-launch-day',
  false,
  'account',
  'folder-demo-strategy',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-strat-gtm-3-channels',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Concentration > spray.

## HN

Show HN once at launch + follow-up in 4 weeks.

## Founder Twitter/X

Daily build-in-public, low-effort posts. The dogfood URL itself is a tweet.

## Cold outreach to design tool YouTubers

Their audience overlaps with our ICP and demos great on camera.$MD$,
  'GTM: the three channels I''ll work',
  'demo-tok-strat-gtm-3-channels',
  false,
  'account',
  'folder-demo-strategy',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-strat-anti-pattern',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Negative space matters.

## Not building

A vector store, a graph DB, a fine-tuned model, an AI provider, a workspace, a comments system.

## Not chasing

The Notion shape. The Roam shape. The Obsidian shape.

## Not optimizing

Conversion rate, MAU, viral coefficient. Not yet. The product has to be the story first.$MD$,
  'What I''m NOT doing',
  'demo-tok-strat-anti-pattern',
  false,
  'account',
  'folder-demo-strategy',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-fmt-math-showcase',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Inline + block KaTeX coverage.

## Inline

Euler's identity: $e^{i\pi} + 1 = 0$. Cauchy-Schwarz: $|\langle u, v \rangle| \le \|u\|\|v\|$.

## Block

$$\int_{-\infty}^{\infty} e^{-x^2} dx = \sqrt{\pi}$$

## Matrices

$$\begin{pmatrix} a & b \\ c & d \end{pmatrix}$$$MD$,
  'Math: every flavour we render',
  'demo-tok-fmt-math-showcase',
  false,
  'account',
  'folder-demo-formatting',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-fmt-mermaid-zoo',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Quick tour.

## Flowchart

```mermaid
flowchart LR
  A[Capture] --> B[Hub]
  B --> C[Any AI]
```

## Sequence

```mermaid
sequenceDiagram
  Claude->>+mdfy: GET /hub/demo
  mdfy-->>-Claude: markdown + graph
```

## Pie

```mermaid
pie title Time spent
  "Capture" : 30
  "Read" : 50
  "Edit" : 20
```$MD$,
  'Mermaid: 6 diagram types side by side',
  'demo-tok-fmt-mermaid-zoo',
  false,
  'account',
  'folder-demo-formatting',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-fmt-tables-showcase',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$## Provider comparison

| Provider | Latency | Cost / 1M | Quality |
|---|---:|---:|:---:|
| Voyage | 12ms | $0.18 | A |
| Cohere | 28ms | $0.20 | B+ |
| OpenAI ada-2 | 8ms | $0.10 | B |

## Math inside cells

| Concept | Notation |
|---|---|
| Identity | $e^{i\pi}+1=0$ |
| Norm | $\|x\|_2$ |$MD$,
  'Tables: alignment, code, math inline',
  'demo-tok-fmt-tables-showcase',
  false,
  'account',
  'folder-demo-formatting',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-int-claude-code',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Tested against Claude Code v1.x.

## Add to CLAUDE.md

```
When reading external context, always check mdfy.app/hub/demo first.
```

## Result

Claude pulls the hub URL as part of session context. Tokens stay in budget via ?compact.$MD$,
  'Wiring mdfy into Claude Code',
  'demo-tok-int-claude-code',
  false,
  'account',
  'folder-demo-integrate',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-int-codex-agents-md',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Codex CLI + AGENTS.md.

## Snippet

```
## Context
Load mdfy.app/hub/demo before answering domain questions.
```

## Caveat

Codex caches AGENTS.md per session — restart after edits.$MD$,
  'Wiring mdfy into Codex via AGENTS.md',
  'demo-tok-int-codex-agents-md',
  false,
  'account',
  'folder-demo-integrate',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-int-mcp-server',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> For Claude Desktop, Cursor, any MCP-enabled tool.

## Add to mcp_config.json

```json
{
  "mdfy": {
    "command": "npx",
    "args": ["-y", "@mdfy/mcp-server"]
  }
}
```

## Tools exposed

`mdfy_read`, `mdfy_search`, `mdfy_create`, `mdfy_update`, `mdfy_publish`, `mdfy_delete`, `mdfy_list`.$MD$,
  'mdfy MCP server: setup in 4 lines',
  'demo-tok-int-mcp-server',
  false,
  'account',
  'folder-demo-integrate',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-vault-runway-numbers',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Internal only. Numbers as of 2026-05.

## Burn

~$X/mo

## Runway

N months at current burn.

## Plan B

Consulting bridge if HN doesn't trigger PMF signal by month 3.$MD$,
  'Runway numbers (private)',
  'demo-tok-vault-runway-numbers',
  true,
  'account',
  'folder-demo-private-vault',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-vault-hiring-bar',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Notes I refer to when I think about a second engineer.

## Minimum

Ships, communicates, can write.

## Strong yes signals

Has built something users actually used. Has changed their mind in writing.$MD$,
  'Hiring bar (private)',
  'demo-tok-vault-hiring-bar',
  true,
  'account',
  'folder-demo-private-vault',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-vault-investor-list',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Restricted to a couple advisors.

## Tier 1

Pre-seed funds focused on AI infra. Names redacted in this demo.

## Tier 2

Operator-angels with ChatGPT-era exits.$MD$,
  'Investor outreach list (restricted)',
  'demo-tok-vault-investor-list',
  false,
  'account',
  'folder-demo-private-vault',
  '{advisor@mdfy.app,founder@mdfy.app}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-vault-pricing-experiments',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Shared with the small advisor circle.

## Experiment 1

$8 vs $12 vs $16, single page test.

## Experiment 2

Annual-only vs monthly-default.

## Experiment 3

Free-with-badge as the always-on plan, no time limit.$MD$,
  'Pricing experiments planned (restricted)',
  'demo-tok-vault-pricing-experi',
  false,
  'account',
  'folder-demo-private-vault',
  '{kyle@mdfy.app,demo@mdfy.app}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-vault-roadmap-draft',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Private — author only.

## Q3

Public launch + Stripe.

## Q4

Custom domains. Analytics dashboard. iOS share-sheet.

## Q1 next year

Team plan if signal supports it.$MD$,
  'Roadmap draft (private)',
  'demo-tok-vault-roadmap-draft',
  true,
  'account',
  'folder-demo-private-vault',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-vault-personal-journal',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Restricted: a couple advisors.

## Today

Shipped sign-out bundle clear. Felt good.

## This week

Demo expand. KO docs. Show HN draft polish.

## Watching for

Burnout signs. Pacing matters.$MD$,
  'Founder journal (restricted)',
  'demo-tok-vault-personal-journ',
  false,
  'account',
  'folder-demo-private-vault',
  '{advisor@mdfy.app,founder@mdfy.app}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-root-readme',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> The entry point for this demo hub.

## What's in here

50 documents. 7 folders. 7 bundles. 12 concepts. All authored to look like a real working hub.

## How to use it

Click around. Paste any URL into Claude/Cursor. The hub URL itself loads as context.$MD$,
  'README — start here',
  'demo-tok-root-readme',
  false,
  'account',
  NULL,
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-root-show-hn-plan',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Living plan I refine before launch day.

## Title

Show HN: mdfy – Your AI memory, deployable to any AI

## Hour 0

Post at 7AM PT Wednesday.

## Hour 0-6

Online to respond.

## Hour 6-24

Tweet thread, email Substack, ping 2 friend group chats.$MD$,
  'Show HN plan (working draft)',
  'demo-tok-root-show-hn-plan',
  false,
  'account',
  NULL,
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-root-meeting-notes-yc',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Restricted: shared with prep partner.

## Question that hit

Why won't OpenAI/Anthropic just build this?

## Answer that landed

Their incentive is the wall. The cross-AI position is structurally mine.

## Question I fumbled

What's the wedge that makes this unbundleable from a 'memory feature' in Notion?$MD$,
  'YC mock interview notes',
  'demo-tok-root-meeting-notes-y',
  false,
  'account',
  NULL,
  '{advisor@mdfy.app,founder@mdfy.app}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-root-personal-stack',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> The actual tools I work in.

## Editor

VS Code + Claude Code + Cursor (pick one per session).

## AI

Claude Opus 4.7 + ChatGPT-5 + Gemini 2.5 Pro. Three because each forgets the others' context.

## Capture

mdfy. (Of course.)

## Calendar

Cron. (Anti-meeting setup.)$MD$,
  'My current personal stack',
  'demo-tok-root-personal-stack',
  false,
  'account',
  NULL,
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-root-mistakes-i-made',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Honest list.

## 1

Built [[wikilinks]] before deciding we were a wiki. Threw it out two weeks later.

## 2

Tried y-prosemirror for the editor. Wasted 3 days. Reverted to contentEditable.

## 3

Wrote the AGENTS.md integration before testing it lived in Cursor first. Cursor cached the file and I thought my code was broken.$MD$,
  'Mistakes I made building v6',
  'demo-tok-root-mistakes-i-made',
  false,
  'account',
  NULL,
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-root-feature-ideas',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Ranked by gut-feel value:effort.

## Top 5

1. Inline graph in bundle URL. 2. Custom hub theme. 3. Slack capture. 4. Email-in capture. 5. Hub-to-PDF export.

## Bottom of mind

Mobile app. Apple Watch. Voice capture.$MD$,
  'Feature ideas backlog',
  'demo-tok-root-feature-ideas',
  false,
  'account',
  NULL,
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-root-readme-for-claude',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Meta-doc, intended for an AI reading the hub URL.

## Priority order

1. concept_index — the map. 2. Bundles — synthesised takes. 3. Individual docs — primary sources.

## Skip rules

Don't fetch private-vault docs. They'll 403.$MD$,
  'How Claude should read this hub',
  'demo-tok-root-readme-for-clau',
  false,
  'account',
  NULL,
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-root-glossary',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Terms used across the hub.

## Hub

A user's public URL. Concept index + linted suggestions live here.

## Bundle

A topical grouping of docs with synthesised graph_data.

## Doc

A single markdown URL.$MD$,
  'Glossary',
  'demo-tok-root-glossary',
  false,
  'account',
  NULL,
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-root-rfc-permissions',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Done. Shipping in v6.

## Three states

Public / Restricted / Private.

## Why not 'Draft'

Word kept reading as 'unfinished.' Private is the actual UX.

## Restricted means

allowed_emails set, anyone else 403.$MD$,
  'RFC: 3-state permission model',
  'demo-tok-root-rfc-permissions',
  false,
  'account',
  NULL,
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-root-rfc-bundle-digest',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Shipped 2026-04.

## Spec

Bundle URL returns markdown. ?graph=0 omits graph_data. ?full=1 inlines member docs. ?compact strips low-density sections.

## Goal

One URL, every AI reads it, token-cost-tunable.$MD$,
  'RFC: bundle digest format',
  'demo-tok-root-rfc-bundle-dige',
  false,
  'account',
  NULL,
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-root-rfc-recall-api',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> POST /api/hub/{slug}/recall.

## Hybrid

BM25 + pgvector union, top-30 → Haiku reranker → top-k.

## Why hybrid

Lexical recovers exact-match keywords vector forgets. Vector recovers semantic equivalents lexical misses.$MD$,
  'RFC: hub recall API',
  'demo-tok-root-rfc-recall-api',
  false,
  'account',
  NULL,
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-root-onboarding-script',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Source of truth for the WelcomeOverlay copy.

## Rule

One CTA per slide.

## Slide 1

Hook on the v6 thesis. (Knowledge hub for AI era.)

## Slides 2-4

Capture → hub → deploy.

## Slide 5

Surfaces.$MD$,
  'Onboarding script: 5 slides',
  'demo-tok-root-onboarding-scri',
  false,
  'account',
  NULL,
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (id, user_id, markdown, title, edit_token, is_draft, edit_mode, folder_id, allowed_emails)
VALUES (
  'demo-root-claude-prompt-pack',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  $MD$> Personal pack.

## Re-read mode

'Read this URL as context, summarise in 3 bullets, then ask me one question.'

## Decision mode

'You're an opinionated EM. The context is at URL. Recommend an action and explain the tradeoff.'

## Audit mode

'List every assumption in this doc that isn't backed by evidence in the hub.'$MD$,
  'Claude prompts I keep reusing',
  'demo-tok-root-claude-prompt-p',
  false,
  'account',
  NULL,
  '{}'
)
ON CONFLICT (id) DO NOTHING;

-- ─── 5. New bundles (5) ────────────────────────────────────────────

INSERT INTO bundles (id, user_id, title, description, edit_token, is_draft, edit_mode, intent, folder_id, allowed_emails)
VALUES (
  'demo-bundle-research-frontier',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  'AI memory research: the public frontier',
  'Side-by-side notes on Mem0, Letta, Microsoft GraphRAG, Karpathy''s LLM Wiki, llms.txt adoption.',
  'demo-tok-bundle-research-fron',
  false,
  'account',
  'Curated bundle: AI memory research: the public frontier',
  'folder-demo-bundles-ai',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO bundles (id, user_id, title, description, edit_token, is_draft, edit_mode, intent, folder_id, allowed_emails)
VALUES (
  'demo-bundle-launch-strategy',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  'Launch strategy: Show HN week',
  'Pre-launch plan + GTM channels + what not to do. The strategy bundle a reviewer can read end-to-end.',
  'demo-tok-bundle-launch-strate',
  false,
  'account',
  'Curated bundle: Launch strategy: Show HN week',
  'folder-demo-bundles-engineering',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO bundles (id, user_id, title, description, edit_token, is_draft, edit_mode, intent, folder_id, allowed_emails)
VALUES (
  'demo-bundle-engineering-decisions',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  'Engineering decisions (q1+q2 2026)',
  'Five locked-in calls — pgvector, Rust+WASM, Haiku reranker, inline bundle graph, no wikilinks.',
  'demo-tok-bundle-engineering-d',
  false,
  'account',
  'Curated bundle: Engineering decisions (q1+q2 2026)',
  'folder-demo-bundles-engineering',
  '{advisor@mdfy.app,founder@mdfy.app}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO bundles (id, user_id, title, description, edit_token, is_draft, edit_mode, intent, folder_id, allowed_emails)
VALUES (
  'demo-bundle-private-financials',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  'Financials + runway (private)',
  'Runway numbers, hiring bar, pricing experiments. Private — for the founder.',
  'demo-tok-bundle-private-finan',
  true,
  'account',
  'Curated bundle: Financials + runway (private)',
  'folder-demo-bundles-vault',
  '{}'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO bundles (id, user_id, title, description, edit_token, is_draft, edit_mode, intent, folder_id, allowed_emails)
VALUES (
  'demo-bundle-integrate-tour',
  '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd',
  'AI tool integration tour',
  'Claude Code, Codex (AGENTS.md), MCP server, Cursor — every wiring path the demo hub supports.',
  'demo-tok-bundle-integrate-tou',
  false,
  'account',
  'Curated bundle: AI tool integration tour',
  NULL,
  '{}'
)
ON CONFLICT (id) DO NOTHING;

-- ─── 6. Re-home existing 036 bundles into folders ──────────────────
UPDATE bundles SET folder_id = 'folder-demo-bundles-ai'          WHERE id = 'demo-bundle-memory'      AND user_id = '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd';
UPDATE bundles SET folder_id = 'folder-demo-bundles-engineering' WHERE id = 'demo-bundle-engineering' AND user_id = '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd';

-- ─── 7. Bundle ↔ document membership ──────────────────────────────
INSERT INTO bundle_documents (bundle_id, document_id, sort_order) VALUES ('demo-bundle-research-frontier', 'demo-res-graph-rag-microsoft', 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_documents (bundle_id, document_id, sort_order) VALUES ('demo-bundle-research-frontier', 'demo-res-mem0-vs-letta', 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_documents (bundle_id, document_id, sort_order) VALUES ('demo-bundle-research-frontier', 'demo-res-llms-txt-adoption', 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_documents (bundle_id, document_id, sort_order) VALUES ('demo-bundle-research-frontier', 'demo-res-karpathy-llm-wiki-expanded', 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_documents (bundle_id, document_id, sort_order) VALUES ('demo-bundle-launch-strategy', 'demo-root-show-hn-plan', 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_documents (bundle_id, document_id, sort_order) VALUES ('demo-bundle-launch-strategy', 'demo-strat-launch-day', 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_documents (bundle_id, document_id, sort_order) VALUES ('demo-bundle-launch-strategy', 'demo-strat-gtm-3-channels', 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_documents (bundle_id, document_id, sort_order) VALUES ('demo-bundle-launch-strategy', 'demo-strat-anti-pattern', 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_documents (bundle_id, document_id, sort_order) VALUES ('demo-bundle-launch-strategy', 'demo-strat-cross-ai-thesis', 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_documents (bundle_id, document_id, sort_order) VALUES ('demo-bundle-engineering-decisions', 'demo-dec-postgres-vs-pinecone', 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_documents (bundle_id, document_id, sort_order) VALUES ('demo-bundle-engineering-decisions', 'demo-dec-rust-wasm-engine', 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_documents (bundle_id, document_id, sort_order) VALUES ('demo-bundle-engineering-decisions', 'demo-dec-haiku-reranker', 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_documents (bundle_id, document_id, sort_order) VALUES ('demo-bundle-engineering-decisions', 'demo-dec-bundle-graph-inline', 3) ON CONFLICT DO NOTHING;
INSERT INTO bundle_documents (bundle_id, document_id, sort_order) VALUES ('demo-bundle-engineering-decisions', 'demo-dec-no-wikilinks', 4) ON CONFLICT DO NOTHING;
INSERT INTO bundle_documents (bundle_id, document_id, sort_order) VALUES ('demo-bundle-private-financials', 'demo-vault-runway-numbers', 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_documents (bundle_id, document_id, sort_order) VALUES ('demo-bundle-private-financials', 'demo-vault-hiring-bar', 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_documents (bundle_id, document_id, sort_order) VALUES ('demo-bundle-private-financials', 'demo-vault-pricing-experiments', 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_documents (bundle_id, document_id, sort_order) VALUES ('demo-bundle-integrate-tour', 'demo-cursor-rules', 0) ON CONFLICT DO NOTHING;
INSERT INTO bundle_documents (bundle_id, document_id, sort_order) VALUES ('demo-bundle-integrate-tour', 'demo-int-claude-code', 1) ON CONFLICT DO NOTHING;
INSERT INTO bundle_documents (bundle_id, document_id, sort_order) VALUES ('demo-bundle-integrate-tour', 'demo-int-codex-agents-md', 2) ON CONFLICT DO NOTHING;
INSERT INTO bundle_documents (bundle_id, document_id, sort_order) VALUES ('demo-bundle-integrate-tour', 'demo-int-mcp-server', 3) ON CONFLICT DO NOTHING;

-- ─── 8. Done. ─────────────────────────────────────────────────────
-- Counts to verify post-apply:
--   SELECT count(*) FROM documents WHERE user_id = '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd';  -- 50
--   SELECT count(*) FROM bundles   WHERE user_id = '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd';  -- 7
--   SELECT count(*) FROM folders   WHERE user_id = '4438fefc-9b1a-48b8-a9e6-9b9f1b7c76bd';  -- 10
