-- 038: Renumber demo account doc + bundle IDs.
--
-- Replaces the semantic IDs seeded in 036 + 037 with opaque
-- 8-char nanoid-style IDs so demo URLs read like real production
-- ones. Preserves rows (graph_data on bundles stays in place).
--
-- Strategy per row:
--   1. INSERT a copy with the new id (carrying every column we care
--      about — graph_data on bundles, markdown on docs, etc.)
--   2. UPDATE bundle_documents FK to point at the new id
--   3. UPDATE concept_index.doc_ids JSONB to rewrite each occurrence
--   4. DELETE the old row (its bundle_documents links are already
--      moved, so the CASCADE has nothing to cascade through)
--
-- Idempotency: not idempotent — re-running this template would
-- generate fresh new IDs and try to copy already-renumbered rows
-- (which would fail at the INSERT step, the new ids don't match
-- the old ids any more). Generate once, apply once.
--
-- Generated by _demo_renumber_generator.py.

BEGIN;

-- ─── Documents ──────────────────────────────────────────────

-- demo-ai-memory-chat → yt2ZZqyI
UPDATE documents SET deleted_at = now() WHERE id = 'demo-ai-memory-chat';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'yt2ZZqyI', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-ai-memory-chat';
UPDATE bundle_documents SET document_id = 'yt2ZZqyI' WHERE document_id = 'demo-ai-memory-chat';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-ai-memory-chat', 'yt2ZZqyI')
 WHERE 'demo-ai-memory-chat' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-ai-memory-chat';

-- demo-decision-graph-url → kxn9T-Vv
UPDATE documents SET deleted_at = now() WHERE id = 'demo-decision-graph-url';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'kxn9T-Vv', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-decision-graph-url';
UPDATE bundle_documents SET document_id = 'kxn9T-Vv' WHERE document_id = 'demo-decision-graph-url';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-decision-graph-url', 'kxn9T-Vv')
 WHERE 'demo-decision-graph-url' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-decision-graph-url';

-- demo-formatting-tour → F1q9U1YP
UPDATE documents SET deleted_at = now() WHERE id = 'demo-formatting-tour';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'F1q9U1YP', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-formatting-tour';
UPDATE bundle_documents SET document_id = 'F1q9U1YP' WHERE document_id = 'demo-formatting-tour';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-formatting-tour', 'F1q9U1YP')
 WHERE 'demo-formatting-tour' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-formatting-tour';

-- demo-strategy-moat → rBRZ_nni
UPDATE documents SET deleted_at = now() WHERE id = 'demo-strategy-moat';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'rBRZ_nni', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-strategy-moat';
UPDATE bundle_documents SET document_id = 'rBRZ_nni' WHERE document_id = 'demo-strategy-moat';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-strategy-moat', 'rBRZ_nni')
 WHERE 'demo-strategy-moat' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-strategy-moat';

-- demo-cursor-rules → TEuiwop8
UPDATE documents SET deleted_at = now() WHERE id = 'demo-cursor-rules';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'TEuiwop8', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-cursor-rules';
UPDATE bundle_documents SET document_id = 'TEuiwop8' WHERE document_id = 'demo-cursor-rules';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-cursor-rules', 'TEuiwop8')
 WHERE 'demo-cursor-rules' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-cursor-rules';

-- demo-karpathy-llm-wiki → T7ZGdpOm
UPDATE documents SET deleted_at = now() WHERE id = 'demo-karpathy-llm-wiki';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'T7ZGdpOm', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-karpathy-llm-wiki';
UPDATE bundle_documents SET document_id = 'T7ZGdpOm' WHERE document_id = 'demo-karpathy-llm-wiki';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-karpathy-llm-wiki', 'T7ZGdpOm')
 WHERE 'demo-karpathy-llm-wiki' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-karpathy-llm-wiki';

-- demo-conv-claude-rust-perf → 77bvsdJ4
UPDATE documents SET deleted_at = now() WHERE id = 'demo-conv-claude-rust-perf';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT '77bvsdJ4', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-conv-claude-rust-perf';
UPDATE bundle_documents SET document_id = '77bvsdJ4' WHERE document_id = 'demo-conv-claude-rust-perf';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-conv-claude-rust-perf', '77bvsdJ4')
 WHERE 'demo-conv-claude-rust-perf' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-conv-claude-rust-perf';

-- demo-conv-gpt5-token-budget → EyW4HU4-
UPDATE documents SET deleted_at = now() WHERE id = 'demo-conv-gpt5-token-budget';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'EyW4HU4-', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-conv-gpt5-token-budget';
UPDATE bundle_documents SET document_id = 'EyW4HU4-' WHERE document_id = 'demo-conv-gpt5-token-budget';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-conv-gpt5-token-budget', 'EyW4HU4-')
 WHERE 'demo-conv-gpt5-token-budget' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-conv-gpt5-token-budget';

-- demo-conv-gemini-image-prompt → qP599HA4
UPDATE documents SET deleted_at = now() WHERE id = 'demo-conv-gemini-image-prompt';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'qP599HA4', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-conv-gemini-image-prompt';
UPDATE bundle_documents SET document_id = 'qP599HA4' WHERE document_id = 'demo-conv-gemini-image-prompt';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-conv-gemini-image-prompt', 'qP599HA4')
 WHERE 'demo-conv-gemini-image-prompt' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-conv-gemini-image-prompt';

-- demo-conv-claude-onboarding → igQZHNzq
UPDATE documents SET deleted_at = now() WHERE id = 'demo-conv-claude-onboarding';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'igQZHNzq', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-conv-claude-onboarding';
UPDATE bundle_documents SET document_id = 'igQZHNzq' WHERE document_id = 'demo-conv-claude-onboarding';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-conv-claude-onboarding', 'igQZHNzq')
 WHERE 'demo-conv-claude-onboarding' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-conv-claude-onboarding';

-- demo-dec-postgres-vs-pinecone → frK9IDOy
UPDATE documents SET deleted_at = now() WHERE id = 'demo-dec-postgres-vs-pinecone';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'frK9IDOy', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-dec-postgres-vs-pinecone';
UPDATE bundle_documents SET document_id = 'frK9IDOy' WHERE document_id = 'demo-dec-postgres-vs-pinecone';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-dec-postgres-vs-pinecone', 'frK9IDOy')
 WHERE 'demo-dec-postgres-vs-pinecone' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-dec-postgres-vs-pinecone';

-- demo-dec-rust-wasm-engine → 5DWOm2ya
UPDATE documents SET deleted_at = now() WHERE id = 'demo-dec-rust-wasm-engine';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT '5DWOm2ya', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-dec-rust-wasm-engine';
UPDATE bundle_documents SET document_id = '5DWOm2ya' WHERE document_id = 'demo-dec-rust-wasm-engine';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-dec-rust-wasm-engine', '5DWOm2ya')
 WHERE 'demo-dec-rust-wasm-engine' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-dec-rust-wasm-engine';

-- demo-dec-haiku-reranker → sB3a5eOG
UPDATE documents SET deleted_at = now() WHERE id = 'demo-dec-haiku-reranker';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'sB3a5eOG', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-dec-haiku-reranker';
UPDATE bundle_documents SET document_id = 'sB3a5eOG' WHERE document_id = 'demo-dec-haiku-reranker';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-dec-haiku-reranker', 'sB3a5eOG')
 WHERE 'demo-dec-haiku-reranker' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-dec-haiku-reranker';

-- demo-dec-bundle-graph-inline → yIpXMsqc
UPDATE documents SET deleted_at = now() WHERE id = 'demo-dec-bundle-graph-inline';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'yIpXMsqc', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-dec-bundle-graph-inline';
UPDATE bundle_documents SET document_id = 'yIpXMsqc' WHERE document_id = 'demo-dec-bundle-graph-inline';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-dec-bundle-graph-inline', 'yIpXMsqc')
 WHERE 'demo-dec-bundle-graph-inline' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-dec-bundle-graph-inline';

-- demo-dec-no-wikilinks → DDxqHKdd
UPDATE documents SET deleted_at = now() WHERE id = 'demo-dec-no-wikilinks';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'DDxqHKdd', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-dec-no-wikilinks';
UPDATE bundle_documents SET document_id = 'DDxqHKdd' WHERE document_id = 'demo-dec-no-wikilinks';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-dec-no-wikilinks', 'DDxqHKdd')
 WHERE 'demo-dec-no-wikilinks' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-dec-no-wikilinks';

-- demo-res-graph-rag-microsoft → 6WkjlKgA
UPDATE documents SET deleted_at = now() WHERE id = 'demo-res-graph-rag-microsoft';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT '6WkjlKgA', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-res-graph-rag-microsoft';
UPDATE bundle_documents SET document_id = '6WkjlKgA' WHERE document_id = 'demo-res-graph-rag-microsoft';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-res-graph-rag-microsoft', '6WkjlKgA')
 WHERE 'demo-res-graph-rag-microsoft' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-res-graph-rag-microsoft';

-- demo-res-mem0-vs-letta → _ybJOqIB
UPDATE documents SET deleted_at = now() WHERE id = 'demo-res-mem0-vs-letta';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT '_ybJOqIB', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-res-mem0-vs-letta';
UPDATE bundle_documents SET document_id = '_ybJOqIB' WHERE document_id = 'demo-res-mem0-vs-letta';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-res-mem0-vs-letta', '_ybJOqIB')
 WHERE 'demo-res-mem0-vs-letta' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-res-mem0-vs-letta';

-- demo-res-llms-txt-adoption → qKRfGtCa
UPDATE documents SET deleted_at = now() WHERE id = 'demo-res-llms-txt-adoption';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'qKRfGtCa', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-res-llms-txt-adoption';
UPDATE bundle_documents SET document_id = 'qKRfGtCa' WHERE document_id = 'demo-res-llms-txt-adoption';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-res-llms-txt-adoption', 'qKRfGtCa')
 WHERE 'demo-res-llms-txt-adoption' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-res-llms-txt-adoption';

-- demo-res-karpathy-llm-wiki-expanded → glqi_Xjw
UPDATE documents SET deleted_at = now() WHERE id = 'demo-res-karpathy-llm-wiki-expanded';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'glqi_Xjw', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-res-karpathy-llm-wiki-expanded';
UPDATE bundle_documents SET document_id = 'glqi_Xjw' WHERE document_id = 'demo-res-karpathy-llm-wiki-expanded';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-res-karpathy-llm-wiki-expanded', 'glqi_Xjw')
 WHERE 'demo-res-karpathy-llm-wiki-expanded' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-res-karpathy-llm-wiki-expanded';

-- demo-res-context-engineering → AXAIfrBG
UPDATE documents SET deleted_at = now() WHERE id = 'demo-res-context-engineering';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'AXAIfrBG', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-res-context-engineering';
UPDATE bundle_documents SET document_id = 'AXAIfrBG' WHERE document_id = 'demo-res-context-engineering';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-res-context-engineering', 'AXAIfrBG')
 WHERE 'demo-res-context-engineering' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-res-context-engineering';

-- demo-strat-cross-ai-thesis → 1tyw7rGT
UPDATE documents SET deleted_at = now() WHERE id = 'demo-strat-cross-ai-thesis';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT '1tyw7rGT', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-strat-cross-ai-thesis';
UPDATE bundle_documents SET document_id = '1tyw7rGT' WHERE document_id = 'demo-strat-cross-ai-thesis';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-strat-cross-ai-thesis', '1tyw7rGT')
 WHERE 'demo-strat-cross-ai-thesis' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-strat-cross-ai-thesis';

-- demo-strat-pricing-model → TQhyhtbt
UPDATE documents SET deleted_at = now() WHERE id = 'demo-strat-pricing-model';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'TQhyhtbt', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-strat-pricing-model';
UPDATE bundle_documents SET document_id = 'TQhyhtbt' WHERE document_id = 'demo-strat-pricing-model';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-strat-pricing-model', 'TQhyhtbt')
 WHERE 'demo-strat-pricing-model' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-strat-pricing-model';

-- demo-strat-launch-day → mXy_aztt
UPDATE documents SET deleted_at = now() WHERE id = 'demo-strat-launch-day';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'mXy_aztt', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-strat-launch-day';
UPDATE bundle_documents SET document_id = 'mXy_aztt' WHERE document_id = 'demo-strat-launch-day';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-strat-launch-day', 'mXy_aztt')
 WHERE 'demo-strat-launch-day' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-strat-launch-day';

-- demo-strat-gtm-3-channels → 8MD8xlLA
UPDATE documents SET deleted_at = now() WHERE id = 'demo-strat-gtm-3-channels';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT '8MD8xlLA', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-strat-gtm-3-channels';
UPDATE bundle_documents SET document_id = '8MD8xlLA' WHERE document_id = 'demo-strat-gtm-3-channels';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-strat-gtm-3-channels', '8MD8xlLA')
 WHERE 'demo-strat-gtm-3-channels' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-strat-gtm-3-channels';

-- demo-strat-anti-pattern → q13ymHpq
UPDATE documents SET deleted_at = now() WHERE id = 'demo-strat-anti-pattern';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'q13ymHpq', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-strat-anti-pattern';
UPDATE bundle_documents SET document_id = 'q13ymHpq' WHERE document_id = 'demo-strat-anti-pattern';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-strat-anti-pattern', 'q13ymHpq')
 WHERE 'demo-strat-anti-pattern' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-strat-anti-pattern';

-- demo-fmt-math-showcase → y3zQ915R
UPDATE documents SET deleted_at = now() WHERE id = 'demo-fmt-math-showcase';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'y3zQ915R', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-fmt-math-showcase';
UPDATE bundle_documents SET document_id = 'y3zQ915R' WHERE document_id = 'demo-fmt-math-showcase';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-fmt-math-showcase', 'y3zQ915R')
 WHERE 'demo-fmt-math-showcase' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-fmt-math-showcase';

-- demo-fmt-mermaid-zoo → 9uh4qUuz
UPDATE documents SET deleted_at = now() WHERE id = 'demo-fmt-mermaid-zoo';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT '9uh4qUuz', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-fmt-mermaid-zoo';
UPDATE bundle_documents SET document_id = '9uh4qUuz' WHERE document_id = 'demo-fmt-mermaid-zoo';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-fmt-mermaid-zoo', '9uh4qUuz')
 WHERE 'demo-fmt-mermaid-zoo' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-fmt-mermaid-zoo';

-- demo-fmt-tables-showcase → hjlgK4OA
UPDATE documents SET deleted_at = now() WHERE id = 'demo-fmt-tables-showcase';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'hjlgK4OA', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-fmt-tables-showcase';
UPDATE bundle_documents SET document_id = 'hjlgK4OA' WHERE document_id = 'demo-fmt-tables-showcase';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-fmt-tables-showcase', 'hjlgK4OA')
 WHERE 'demo-fmt-tables-showcase' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-fmt-tables-showcase';

-- demo-int-claude-code → iok3gZo6
UPDATE documents SET deleted_at = now() WHERE id = 'demo-int-claude-code';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'iok3gZo6', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-int-claude-code';
UPDATE bundle_documents SET document_id = 'iok3gZo6' WHERE document_id = 'demo-int-claude-code';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-int-claude-code', 'iok3gZo6')
 WHERE 'demo-int-claude-code' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-int-claude-code';

-- demo-int-codex-agents-md → y4sEEo1R
UPDATE documents SET deleted_at = now() WHERE id = 'demo-int-codex-agents-md';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'y4sEEo1R', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-int-codex-agents-md';
UPDATE bundle_documents SET document_id = 'y4sEEo1R' WHERE document_id = 'demo-int-codex-agents-md';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-int-codex-agents-md', 'y4sEEo1R')
 WHERE 'demo-int-codex-agents-md' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-int-codex-agents-md';

-- demo-int-mcp-server → PrxR1Uj4
UPDATE documents SET deleted_at = now() WHERE id = 'demo-int-mcp-server';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'PrxR1Uj4', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-int-mcp-server';
UPDATE bundle_documents SET document_id = 'PrxR1Uj4' WHERE document_id = 'demo-int-mcp-server';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-int-mcp-server', 'PrxR1Uj4')
 WHERE 'demo-int-mcp-server' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-int-mcp-server';

-- demo-vault-runway-numbers → eEcvdmGo
UPDATE documents SET deleted_at = now() WHERE id = 'demo-vault-runway-numbers';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'eEcvdmGo', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-vault-runway-numbers';
UPDATE bundle_documents SET document_id = 'eEcvdmGo' WHERE document_id = 'demo-vault-runway-numbers';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-vault-runway-numbers', 'eEcvdmGo')
 WHERE 'demo-vault-runway-numbers' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-vault-runway-numbers';

-- demo-vault-hiring-bar → 0aq2bdc9
UPDATE documents SET deleted_at = now() WHERE id = 'demo-vault-hiring-bar';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT '0aq2bdc9', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-vault-hiring-bar';
UPDATE bundle_documents SET document_id = '0aq2bdc9' WHERE document_id = 'demo-vault-hiring-bar';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-vault-hiring-bar', '0aq2bdc9')
 WHERE 'demo-vault-hiring-bar' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-vault-hiring-bar';

-- demo-vault-investor-list → 0-yqUYQx
UPDATE documents SET deleted_at = now() WHERE id = 'demo-vault-investor-list';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT '0-yqUYQx', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-vault-investor-list';
UPDATE bundle_documents SET document_id = '0-yqUYQx' WHERE document_id = 'demo-vault-investor-list';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-vault-investor-list', '0-yqUYQx')
 WHERE 'demo-vault-investor-list' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-vault-investor-list';

-- demo-vault-pricing-experiments → VZI8WpeB
UPDATE documents SET deleted_at = now() WHERE id = 'demo-vault-pricing-experiments';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'VZI8WpeB', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-vault-pricing-experiments';
UPDATE bundle_documents SET document_id = 'VZI8WpeB' WHERE document_id = 'demo-vault-pricing-experiments';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-vault-pricing-experiments', 'VZI8WpeB')
 WHERE 'demo-vault-pricing-experiments' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-vault-pricing-experiments';

-- demo-vault-roadmap-draft → 2ouC5IH3
UPDATE documents SET deleted_at = now() WHERE id = 'demo-vault-roadmap-draft';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT '2ouC5IH3', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-vault-roadmap-draft';
UPDATE bundle_documents SET document_id = '2ouC5IH3' WHERE document_id = 'demo-vault-roadmap-draft';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-vault-roadmap-draft', '2ouC5IH3')
 WHERE 'demo-vault-roadmap-draft' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-vault-roadmap-draft';

-- demo-vault-personal-journal → khPQfDFc
UPDATE documents SET deleted_at = now() WHERE id = 'demo-vault-personal-journal';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'khPQfDFc', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-vault-personal-journal';
UPDATE bundle_documents SET document_id = 'khPQfDFc' WHERE document_id = 'demo-vault-personal-journal';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-vault-personal-journal', 'khPQfDFc')
 WHERE 'demo-vault-personal-journal' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-vault-personal-journal';

-- demo-root-readme → csFtDM3c
UPDATE documents SET deleted_at = now() WHERE id = 'demo-root-readme';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'csFtDM3c', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-root-readme';
UPDATE bundle_documents SET document_id = 'csFtDM3c' WHERE document_id = 'demo-root-readme';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-root-readme', 'csFtDM3c')
 WHERE 'demo-root-readme' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-root-readme';

-- demo-root-show-hn-plan → r_HaRypO
UPDATE documents SET deleted_at = now() WHERE id = 'demo-root-show-hn-plan';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'r_HaRypO', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-root-show-hn-plan';
UPDATE bundle_documents SET document_id = 'r_HaRypO' WHERE document_id = 'demo-root-show-hn-plan';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-root-show-hn-plan', 'r_HaRypO')
 WHERE 'demo-root-show-hn-plan' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-root-show-hn-plan';

-- demo-root-meeting-notes-yc → 1fCfQkpa
UPDATE documents SET deleted_at = now() WHERE id = 'demo-root-meeting-notes-yc';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT '1fCfQkpa', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-root-meeting-notes-yc';
UPDATE bundle_documents SET document_id = '1fCfQkpa' WHERE document_id = 'demo-root-meeting-notes-yc';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-root-meeting-notes-yc', '1fCfQkpa')
 WHERE 'demo-root-meeting-notes-yc' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-root-meeting-notes-yc';

-- demo-root-personal-stack → UaxcbLwD
UPDATE documents SET deleted_at = now() WHERE id = 'demo-root-personal-stack';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'UaxcbLwD', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-root-personal-stack';
UPDATE bundle_documents SET document_id = 'UaxcbLwD' WHERE document_id = 'demo-root-personal-stack';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-root-personal-stack', 'UaxcbLwD')
 WHERE 'demo-root-personal-stack' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-root-personal-stack';

-- demo-root-mistakes-i-made → bDVLxgav
UPDATE documents SET deleted_at = now() WHERE id = 'demo-root-mistakes-i-made';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'bDVLxgav', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-root-mistakes-i-made';
UPDATE bundle_documents SET document_id = 'bDVLxgav' WHERE document_id = 'demo-root-mistakes-i-made';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-root-mistakes-i-made', 'bDVLxgav')
 WHERE 'demo-root-mistakes-i-made' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-root-mistakes-i-made';

-- demo-root-feature-ideas → wyULEr1h
UPDATE documents SET deleted_at = now() WHERE id = 'demo-root-feature-ideas';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'wyULEr1h', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-root-feature-ideas';
UPDATE bundle_documents SET document_id = 'wyULEr1h' WHERE document_id = 'demo-root-feature-ideas';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-root-feature-ideas', 'wyULEr1h')
 WHERE 'demo-root-feature-ideas' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-root-feature-ideas';

-- demo-root-readme-for-claude → NFnDceE2
UPDATE documents SET deleted_at = now() WHERE id = 'demo-root-readme-for-claude';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'NFnDceE2', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-root-readme-for-claude';
UPDATE bundle_documents SET document_id = 'NFnDceE2' WHERE document_id = 'demo-root-readme-for-claude';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-root-readme-for-claude', 'NFnDceE2')
 WHERE 'demo-root-readme-for-claude' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-root-readme-for-claude';

-- demo-root-glossary → _bhW7pVA
UPDATE documents SET deleted_at = now() WHERE id = 'demo-root-glossary';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT '_bhW7pVA', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-root-glossary';
UPDATE bundle_documents SET document_id = '_bhW7pVA' WHERE document_id = 'demo-root-glossary';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-root-glossary', '_bhW7pVA')
 WHERE 'demo-root-glossary' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-root-glossary';

-- demo-root-rfc-permissions → El2-Kzy6
UPDATE documents SET deleted_at = now() WHERE id = 'demo-root-rfc-permissions';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'El2-Kzy6', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-root-rfc-permissions';
UPDATE bundle_documents SET document_id = 'El2-Kzy6' WHERE document_id = 'demo-root-rfc-permissions';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-root-rfc-permissions', 'El2-Kzy6')
 WHERE 'demo-root-rfc-permissions' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-root-rfc-permissions';

-- demo-root-rfc-bundle-digest → 2WqRPNiV
UPDATE documents SET deleted_at = now() WHERE id = 'demo-root-rfc-bundle-digest';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT '2WqRPNiV', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-root-rfc-bundle-digest';
UPDATE bundle_documents SET document_id = '2WqRPNiV' WHERE document_id = 'demo-root-rfc-bundle-digest';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-root-rfc-bundle-digest', '2WqRPNiV')
 WHERE 'demo-root-rfc-bundle-digest' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-root-rfc-bundle-digest';

-- demo-root-rfc-recall-api → OGySiVoO
UPDATE documents SET deleted_at = now() WHERE id = 'demo-root-rfc-recall-api';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'OGySiVoO', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-root-rfc-recall-api';
UPDATE bundle_documents SET document_id = 'OGySiVoO' WHERE document_id = 'demo-root-rfc-recall-api';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-root-rfc-recall-api', 'OGySiVoO')
 WHERE 'demo-root-rfc-recall-api' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-root-rfc-recall-api';

-- demo-root-onboarding-script → Ts4Vh6Zw
UPDATE documents SET deleted_at = now() WHERE id = 'demo-root-onboarding-script';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'Ts4Vh6Zw', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-root-onboarding-script';
UPDATE bundle_documents SET document_id = 'Ts4Vh6Zw' WHERE document_id = 'demo-root-onboarding-script';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-root-onboarding-script', 'Ts4Vh6Zw')
 WHERE 'demo-root-onboarding-script' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-root-onboarding-script';

-- demo-root-claude-prompt-pack → wzixoDcN
UPDATE documents SET deleted_at = now() WHERE id = 'demo-root-claude-prompt-pack';
INSERT INTO documents (id, user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent)
SELECT 'wzixoDcN', user_id, markdown, title, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, source, sort_order, intent FROM documents WHERE id = 'demo-root-claude-prompt-pack';
UPDATE bundle_documents SET document_id = 'wzixoDcN' WHERE document_id = 'demo-root-claude-prompt-pack';
UPDATE concept_index
   SET doc_ids = array_replace(doc_ids, 'demo-root-claude-prompt-pack', 'wzixoDcN')
 WHERE 'demo-root-claude-prompt-pack' = ANY(doc_ids);
DELETE FROM documents WHERE id = 'demo-root-claude-prompt-pack';

-- ─── Bundles ────────────────────────────────────────────────

-- demo-bundle-memory → wa-K_2rF
INSERT INTO bundles (id, user_id, title, description, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, intent, graph_data, graph_generated_at, layout)
SELECT 'wa-K_2rF', user_id, title, description, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, intent, graph_data, graph_generated_at, layout FROM bundles WHERE id = 'demo-bundle-memory';
UPDATE bundle_documents SET bundle_id = 'wa-K_2rF' WHERE bundle_id = 'demo-bundle-memory';
DELETE FROM bundles WHERE id = 'demo-bundle-memory';

-- demo-bundle-engineering → 8IkpnVgX
INSERT INTO bundles (id, user_id, title, description, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, intent, graph_data, graph_generated_at, layout)
SELECT '8IkpnVgX', user_id, title, description, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, intent, graph_data, graph_generated_at, layout FROM bundles WHERE id = 'demo-bundle-engineering';
UPDATE bundle_documents SET bundle_id = '8IkpnVgX' WHERE bundle_id = 'demo-bundle-engineering';
DELETE FROM bundles WHERE id = 'demo-bundle-engineering';

-- demo-bundle-research-frontier → wpwVCSDF
INSERT INTO bundles (id, user_id, title, description, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, intent, graph_data, graph_generated_at, layout)
SELECT 'wpwVCSDF', user_id, title, description, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, intent, graph_data, graph_generated_at, layout FROM bundles WHERE id = 'demo-bundle-research-frontier';
UPDATE bundle_documents SET bundle_id = 'wpwVCSDF' WHERE bundle_id = 'demo-bundle-research-frontier';
DELETE FROM bundles WHERE id = 'demo-bundle-research-frontier';

-- demo-bundle-launch-strategy → DlrrKcQ2
INSERT INTO bundles (id, user_id, title, description, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, intent, graph_data, graph_generated_at, layout)
SELECT 'DlrrKcQ2', user_id, title, description, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, intent, graph_data, graph_generated_at, layout FROM bundles WHERE id = 'demo-bundle-launch-strategy';
UPDATE bundle_documents SET bundle_id = 'DlrrKcQ2' WHERE bundle_id = 'demo-bundle-launch-strategy';
DELETE FROM bundles WHERE id = 'demo-bundle-launch-strategy';

-- demo-bundle-engineering-decisions → aYlO8o98
INSERT INTO bundles (id, user_id, title, description, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, intent, graph_data, graph_generated_at, layout)
SELECT 'aYlO8o98', user_id, title, description, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, intent, graph_data, graph_generated_at, layout FROM bundles WHERE id = 'demo-bundle-engineering-decisions';
UPDATE bundle_documents SET bundle_id = 'aYlO8o98' WHERE bundle_id = 'demo-bundle-engineering-decisions';
DELETE FROM bundles WHERE id = 'demo-bundle-engineering-decisions';

-- demo-bundle-private-financials → efMRhowO
INSERT INTO bundles (id, user_id, title, description, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, intent, graph_data, graph_generated_at, layout)
SELECT 'efMRhowO', user_id, title, description, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, intent, graph_data, graph_generated_at, layout FROM bundles WHERE id = 'demo-bundle-private-financials';
UPDATE bundle_documents SET bundle_id = 'efMRhowO' WHERE bundle_id = 'demo-bundle-private-financials';
DELETE FROM bundles WHERE id = 'demo-bundle-private-financials';

-- demo-bundle-integrate-tour → EJbI7cto
INSERT INTO bundles (id, user_id, title, description, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, intent, graph_data, graph_generated_at, layout)
SELECT 'EJbI7cto', user_id, title, description, edit_token, created_at, updated_at, view_count, is_draft, edit_mode, folder_id, allowed_emails, allowed_editors, intent, graph_data, graph_generated_at, layout FROM bundles WHERE id = 'demo-bundle-integrate-tour';
UPDATE bundle_documents SET bundle_id = 'EJbI7cto' WHERE bundle_id = 'demo-bundle-integrate-tour';
DELETE FROM bundles WHERE id = 'demo-bundle-integrate-tour';

COMMIT;

-- Post-apply verification:
--   SELECT id, title FROM documents WHERE user_id = '<DEMO_USER_ID>' LIMIT 5;
--     (every id should look like 'aB3_xY9z', NOT 'demo-...')
--   SELECT id, title FROM bundles   WHERE user_id = '<DEMO_USER_ID>';
