-- 046_document_summary.sql
--
-- Per-doc LLM summary for the compact hub digest. Phase A.2 of the
-- MWBench-driven compact-accuracy work: the first-paragraph extract
-- (A.1, code-only, no schema) recovered ~20 percentage points, but
-- some docs lead with metadata noise ("Captured from Claude on …") so
-- the first paragraph is a weak signal.
--
-- This column holds a 1-2 sentence summary generated by Claude Haiku
-- at doc save time and on a one-shot backfill for existing docs. The
-- compact digest renderer prefers `summary` when present, falls back
-- to the first-paragraph extractor when null.
--
-- Cost: ~$0.001 per save with claude-haiku-4-5, ~$0.07 total to
-- backfill the existing raymindai corpus (71 docs).

ALTER TABLE documents
  ADD COLUMN IF NOT EXISTS summary TEXT;

ALTER TABLE documents
  ADD COLUMN IF NOT EXISTS summary_model TEXT;

ALTER TABLE documents
  ADD COLUMN IF NOT EXISTS summary_generated_at TIMESTAMPTZ;

-- Partial index: only the rows that still need a summary. Used by the
-- backfill cron / one-shot script to find candidates without scanning
-- the whole table. Drops to zero rows once backfill is done.
CREATE INDEX IF NOT EXISTS documents_summary_missing_idx
  ON documents (id)
  WHERE summary IS NULL
    AND is_draft = false
    AND deleted_at IS NULL;
