// Generated by style-dictionary.config.mjs from design-tokens/accent-palette.json. Edit the JSON; never this file.

package wiki.memory.memorywiki.ui.theme

import androidx.compose.ui.graphics.Color

/** Picker group. Pickers render Vivid first, then Muted under a section header. */
enum class AccentGroup { Vivid, Muted }

/** User-selectable accent palette. Mirrors apps/web/src/lib/_accent.generated.ts
 *  minus the web-only entries (green/teal/red/yellow). */
enum class AccentColorChoice(
    val key: String,
    val dark: Color,
    val light: Color,
    val group: AccentGroup,
) {
    Lime("lime", Color(0xFFB5FF1Au.toInt()), Color(0xFF5BC700u.toInt()), AccentGroup.Vivid),
    Orange("orange", Color(0xFFFB923Cu.toInt()), Color(0xFFEA580Cu.toInt()), AccentGroup.Vivid),
    Blue("blue", Color(0xFF60A5FAu.toInt()), Color(0xFF2563EBu.toInt()), AccentGroup.Vivid),
    Purple("purple", Color(0xFFA78BFAu.toInt()), Color(0xFF7C3AEDu.toInt()), AccentGroup.Vivid),
    Pink("pink", Color(0xFFF472B6u.toInt()), Color(0xFFEC4899u.toInt()), AccentGroup.Vivid),
    Gray("gray", Color(0xFFA1A1AAu.toInt()), Color(0xFF52525Bu.toInt()), AccentGroup.Vivid),
    Sage("sage", Color(0xFF94B49Fu.toInt()), Color(0xFF5E8669u.toInt()), AccentGroup.Muted),
    Slate("slate", Color(0xFF7C8DA8u.toInt()), Color(0xFF536175u.toInt()), AccentGroup.Muted),
    Sand("sand", Color(0xFFC7B299u.toInt()), Color(0xFF8C7656u.toInt()), AccentGroup.Muted),
    Mauve("mauve", Color(0xFFB193A6u.toInt()), Color(0xFF7B5E72u.toInt()), AccentGroup.Muted),
    Rose("rose", Color(0xFFC99595u.toInt()), Color(0xFF965C5Cu.toInt()), AccentGroup.Muted),
    Iris("iris", Color(0xFF7E7FB0u.toInt()), Color(0xFF52537Au.toInt()), AccentGroup.Muted);

    companion object {
        /** Default = Gray (neutral) per v8 brand decision 2026-05-31.
         *  Lime stays in the picker as an opt-in choice. */
        fun from(key: String?): AccentColorChoice =
            entries.firstOrNull { it.key.equals(key, ignoreCase = true) } ?: Gray
    }
}
