/*
 * Brand — Android facade over the canonical design tokens.
 *
 * Color values delegate to `BrandTokens` (generated by Style
 * Dictionary from /design-tokens/ JSON sources, never edit
 * BrandTokens.generated.kt directly). Run `npm run tokens:build`
 * at repo root after changing a token.
 *
 * Rules of thumb (from v8 color-balance feedback):
 *   - Body, chips, buttons stay INK (`TextPrimary`). Accent role
 *     resolves to neutral text-primary ink; status semantics live
 *     in the Micro* family used only for small dots / badges /
 *     icons.
 *   - No Material You dynamic color. App is dark-only.
 *   - MicroLime is reserved for public-status / live badges and
 *     tiny dots; it is NOT the brand key color.
 *
 * Why a facade instead of using BrandTokens directly?
 *   Existing call sites all reach for `Brand.X` so the facade
 *   keeps them compiling. BrandTokens only knows opaque hex;
 *   translucent variants (AccentDim, BorderDim, ToggleBg) and
 *   the secondary `Canvas` shade live here as compositions on
 *   top of the generated primitives.
 */

package wiki.memory.memorywiki.ui.theme

import androidx.compose.foundation.shape.CornerSize
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Shapes
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object Brand {
    // ─── Surface tokens (delegated to BrandTokens.generated.kt) ───

    val Background = BrandTokens.Background

    /** Even darker — used behind split-pane chrome. Not in tokens
     *  yet (only one consumer). Promote when a second use surfaces. */
    val Canvas = Color(0xFF070708)

    val Surface = BrandTokens.Surface

    val SheetBg = BrandTokens.SheetBg

    val Border = BrandTokens.Border
    val BorderDim = BrandTokens.Border.copy(alpha = 0.6f)

    /** Toggle hover / pressed background — surface at 80% alpha. */
    val ToggleBg = BrandTokens.Surface.copy(alpha = 0.8f)

    // ─── Text tokens ───
    val TextPrimary = BrandTokens.TextPrimary
    val TextSecondary = BrandTokens.TextSecondary
    val TextMuted = BrandTokens.TextMuted
    val TextFaint = BrandTokens.TextFaint

    // ─── Default accent (v8: neutral ink, not lime) ───
    val Accent = BrandTokens.Accent
    val AccentDim = BrandTokens.Accent.copy(alpha = 0.08f)

    // ─── Micro-color tokens. Use only in small dots / badges. ───
    val MicroInfo = BrandTokens.MicroInfo
    val MicroWarn = BrandTokens.MicroWarn
    val MicroRed = BrandTokens.MicroRed
    val MicroLime = BrandTokens.MicroLime
    val MicroPurple = BrandTokens.MicroAi  // alias — bundle deploy used purple

    // ─── Shape ───
    val Shapes = Shapes(
        extraSmall = RoundedCornerShape(6.dp),
        small = RoundedCornerShape(10.dp),
        medium = RoundedCornerShape(14.dp),
        large = RoundedCornerShape(20.dp),
        extraLarge = RoundedCornerShape(28.dp),
    )

    val SheetCorner: CornerSize = CornerSize(28.dp)
}

/* AccentColorChoice + AccentGroup live in _AccentCatalog.generated.kt
 * (same package), produced by Style Dictionary from
 * design-tokens/accent-palette.json. Edit the JSON, run
 * `npm run tokens:build` from repo root, commit both. */
