// Generated by Style Dictionary. Edit design-tokens/ — never this file.

package wiki.memory.memorywiki.ui.theme

import androidx.compose.ui.graphics.Color

object BrandTokens {
    val Background = Color(0xFF15151Au.toInt())
    val Surface = Color(0xFF18181Bu.toInt())
    // SurfaceHover: rgba/literal: rgba(255, 255, 255, 0.03)
    val SheetBg = Color(0xFF111114u.toInt())
    val Border = Color(0xFF27272Au.toInt())
    // BorderDim: rgba/literal: rgba(39, 39, 42, 0.6)
    val TextPrimary = Color(0xFFFAFAFAu.toInt())
    val TextSecondary = Color(0xFFD4D4D8u.toInt())
    val TextMuted = Color(0xFFA1A1AAu.toInt())
    val TextFaint = Color(0xFF8A8A91u.toInt())
    val Accent = Color(0xFFFAFAFAu.toInt())
    // AccentDim: rgba/literal: rgba(255, 255, 255, 0.08)
    val MicroLime = Color(0xFFB5FF1Au.toInt())
    val MicroOrange = Color(0xFFFF6B1Au.toInt())
    val MicroAi = Color(0xFF8B5CF6u.toInt())
    val MicroInfo = Color(0xFF60A5FAu.toInt())
    val MicroWarn = Color(0xFFFBBF24u.toInt())
    val MicroRed = Color(0xFFEF4444u.toInt())
    val MicroPink = Color(0xFFFF2A7Du.toInt())
}
