/*
 * Brand — Android facade over the canonical design tokens.
 *
 * Color values delegate to `BrandTokens` (generated by Style
 * Dictionary from /design-tokens/ JSON sources, never edit
 * BrandTokens.generated.kt directly). Run `npm run tokens:build`
 * at repo root after changing a token.
 *
 * Rules of thumb (from v8 color-balance feedback):
 *   - Body, chips, buttons stay INK (`TextPrimary`). Accent role
 *     resolves to neutral text-primary ink; status semantics live
 *     in the Micro* family used only for small dots / badges /
 *     icons.
 *   - No Material You dynamic color. App is dark-only.
 *   - MicroLime is reserved for public-status / live badges and
 *     tiny dots; it is NOT the brand key color.
 *
 * Why a facade instead of using BrandTokens directly?
 *   Existing call sites all reach for `Brand.X` so the facade
 *   keeps them compiling. BrandTokens only knows opaque hex;
 *   translucent variants (AccentDim, BorderDim, ToggleBg) and
 *   the secondary `Canvas` shade live here as compositions on
 *   top of the generated primitives.
 */

package wiki.memory.memorywiki.ui.theme

import androidx.compose.foundation.shape.CornerSize
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Shapes
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object Brand {
    // ─── Surface tokens (delegated to BrandTokens.generated.kt) ───

    val Background = BrandTokens.Background

    /** Even darker — used behind split-pane chrome. Not in tokens
     *  yet (only one consumer). Promote when a second use surfaces. */
    val Canvas = Color(0xFF070708)

    val Surface = BrandTokens.Surface

    val SheetBg = BrandTokens.SheetBg

    val Border = BrandTokens.Border
    val BorderDim = BrandTokens.Border.copy(alpha = 0.6f)

    /** Toggle hover / pressed background — surface at 80% alpha. */
    val ToggleBg = BrandTokens.Surface.copy(alpha = 0.8f)

    // ─── Text tokens ───
    val TextPrimary = BrandTokens.TextPrimary
    val TextSecondary = BrandTokens.TextSecondary
    val TextMuted = BrandTokens.TextMuted
    val TextFaint = BrandTokens.TextFaint

    // ─── Default accent (v8: neutral ink, not lime) ───
    val Accent = BrandTokens.Accent
    val AccentDim = BrandTokens.Accent.copy(alpha = 0.08f)

    // ─── Micro-color tokens. Use only in small dots / badges. ───
    val MicroInfo = BrandTokens.MicroInfo
    val MicroWarn = BrandTokens.MicroWarn
    val MicroRed = BrandTokens.MicroRed
    val MicroLime = BrandTokens.MicroLime
    val MicroPurple = BrandTokens.MicroAi  // alias — bundle deploy used purple

    // ─── Shape ───
    val Shapes = Shapes(
        extraSmall = RoundedCornerShape(6.dp),
        small = RoundedCornerShape(10.dp),
        medium = RoundedCornerShape(14.dp),
        large = RoundedCornerShape(20.dp),
        extraLarge = RoundedCornerShape(28.dp),
    )

    val SheetCorner: CornerSize = CornerSize(28.dp)
}

/** Picker group. Pickers render Vivid first, then Muted under a section
 *  header. Keep in sync with apps/web/src/lib/theme-options.ts. */
enum class AccentGroup { Vivid, Muted }

/** Optional accent palette (matches the web SettingsEmbed picker).
 *
 *  Two groups: Vivid (saturated, legacy) + Muted (v8 quiet direction).
 *  Web has more vivid entries (green/teal/red/yellow) — Android keeps
 *  the original 6 to avoid swamping the small picker; if a user picks
 *  one of those on web, Android's `from(...)` falls back to Gray.
 *
 *  Adding/removing entries here also requires:
 *   - apps/web/src/lib/theme-options.ts (AccentColor + ACCENT_COLORS)
 *   - apps/web/src/app/globals.css ([data-accent="..."] blocks)
 *   - apps/web/src/app/api/user/profile/route.ts (ACCENT_KEYS whitelist)
 */
enum class AccentColorChoice(val key: String, val dark: Color, val light: Color, val group: AccentGroup) {
    // ── Vivid (legacy palette) ──
    Lime("lime", Color(0xFFB5FF1A), Color(0xFF5BC700), AccentGroup.Vivid),
    Orange("orange", Color(0xFFFB923C), Color(0xFFEA580C), AccentGroup.Vivid),
    Blue("blue", Color(0xFF60A5FA), Color(0xFF2563EB), AccentGroup.Vivid),
    Purple("purple", Color(0xFFA78BFA), Color(0xFF7C3AED), AccentGroup.Vivid),
    Pink("pink", Color(0xFFF472B6), Color(0xFFDB2777), AccentGroup.Vivid),
    Gray("gray", Color(0xFFA1A1AA), Color(0xFF52525B), AccentGroup.Vivid),
    // ── Muted (v8 quiet-by-default direction) ──
    Sage("sage", Color(0xFF94B49F), Color(0xFF5E8669), AccentGroup.Muted),
    Slate("slate", Color(0xFF7C8DA8), Color(0xFF536175), AccentGroup.Muted),
    Sand("sand", Color(0xFFC7B299), Color(0xFF8C7656), AccentGroup.Muted),
    Mauve("mauve", Color(0xFFB193A6), Color(0xFF7B5E72), AccentGroup.Muted),
    Rose("rose", Color(0xFFC99595), Color(0xFF965C5C), AccentGroup.Muted),
    Iris("iris", Color(0xFF7E7FB0), Color(0xFF52537A), AccentGroup.Muted);

    companion object {
        fun from(key: String?): AccentColorChoice =
            // Default = Gray (neutral) per v8 brand decision 2026-05-31.
            // Lime stays in the picker as an opt-in choice.
            entries.firstOrNull { it.key.equals(key, ignoreCase = true) } ?: Gray
    }
}
