"use client";

import { useState } from "react";
import { VariantNav } from "../VariantNav";
import "./glass.css";

export function GlassVariant() {
  const [streamedText, setStreamedText] = useState("");
  const [showModal, setShowModal] = useState(false);
  const fullText =
    "Your weekly digest: 12 captures this week, clustered into 3 themes. " +
    "Memory.Wiki noticed a strong connection between your TypeScript notes " +
    "and the design system you started capturing on Thursday.";

  const startStream = () => {
    setStreamedText("");
    let i = 0;
    const interval = setInterval(() => {
      i++;
      setStreamedText(fullText.slice(0, i));
      if (i >= fullText.length) clearInterval(interval);
    }, 18);
  };

  return (
    <div className="v8-glass">
      <VariantNav />

      {/* Ambient color wash behind everything */}
      <div className="ambient" aria-hidden />

      <section className="hero">
        <div className="badge">v8 · Liquid Glass</div>
        <h1 className="display">
          Stop re-explaining
          <br />
          your context to{" "}
          <span className="gradient-text">every AI.</span>
        </h1>
        <p className="hero-sub">
          One URL every AI fetches. Yours, your team&apos;s, or your community&apos;s.
        </p>
        <div className="cta-row">
          <button className="btn-primary">
            <span>Start your Memory.Wiki</span>
            <span className="btn-glow" aria-hidden />
          </button>
          <button className="btn-ghost">See an example →</button>
        </div>
      </section>

      {/* Palette */}
      <section className="section">
        <h2 className="section-title">Vibrant palette · materials</h2>
        <p className="section-lede">
          deep neutral bases · vibrant accents · translucent surfaces with backdrop-filter
        </p>
        <div className="palette-grid">
          <Swatch label="Base" hex="#0a0a0f" />
          <Swatch label="Glass surface" hex="rgba(255,255,255,0.04)" />
          <Swatch label="Glass elevated" hex="rgba(255,255,255,0.08)" />
          <Swatch label="Text" hex="#ffffff" />
          <Swatch label="Muted" hex="#9aa0ac" />
          <Swatch label="Accent" hex="#fb923c" />
          <Swatch label="AI · Blue" hex="#5e9bff" />
          <Swatch label="AI · Violet" hex="#9b8cff" />
        </div>
      </section>

      {/* Cards */}
      <section className="section">
        <h2 className="section-title">Glass cards</h2>
        <p className="section-lede">
          hairline borders · backdrop blur · soft shadow · AI carries a vibrant halo
        </p>
        <div className="card-row">
          <div className="card card-user">
            <div className="card-meta">
              <div className="avatar">R</div>
              <span className="card-author">raymind</span>
              <span className="card-time">2h ago</span>
            </div>
            <h3 className="card-title">v8 thinking — capture vs memory</h3>
            <p className="card-body">
              Memory.Wiki 이 메모리 레이어가 되려면 나에 대해서 잘 알아야 함.
              그래서 capture everything 이 자연스러운 입구.
            </p>
            <div className="card-tags">
              <span className="tag">v8</span>
              <span className="tag">thinking</span>
            </div>
          </div>

          <div className="card card-ai">
            <div className="ai-halo" aria-hidden />
            <div className="card-meta">
              <span className="badge-ai">
                <span className="sparkle">✦</span>
                Generated by Claude
              </span>
              <span className="card-time">Sunday digest</span>
            </div>
            <h3 className="card-title">Weekly synthesis · 3 themes emerged</h3>
            <p className="card-body">
              You captured 12 docs this week across TypeScript patterns, v8
              design direction, and cross-AI memory thinking. Strongest signal
              between Thursday&apos;s design notes and Monday&apos;s v8 plan.
            </p>
            <div className="card-tags">
              <span className="tag tag-ai">digest</span>
              <span className="tag tag-ai">synthesis</span>
            </div>
          </div>

          <div className="card card-user">
            <div className="card-meta">
              <div className="avatar">R</div>
              <span className="card-author">raymind</span>
              <span className="card-footnote">edited — originally Claude</span>
            </div>
            <h3 className="card-title">My current focus</h3>
            <p className="card-body">
              Shipping Memory.Wiki v8 over 20 weeks. Capture → Organize → Use
              framework. Cross-AI delivery is the wedge giants cannot build.
            </p>
            <div className="card-tags">
              <span className="tag">focus</span>
              <span className="tag">v8</span>
            </div>
          </div>
        </div>
      </section>

      {/* Streaming */}
      <section className="section">
        <h2 className="section-title">Streaming with vibrancy</h2>
        <div className="card card-ai streaming-demo">
          <div className="ai-halo" aria-hidden />
          <div className="card-meta">
            <span className="badge-ai">
              <span className="sparkle">✦</span>
              Memory.Wiki AI
            </span>
            <button className="stream-btn" onClick={startStream}>
              Generate again
            </button>
          </div>
          <p className="card-body streaming-text">
            {streamedText || (
              <span className="streaming-prompt">Click &ldquo;Generate again&rdquo; →</span>
            )}
            {streamedText && streamedText.length < fullText.length && (
              <span className="cursor" />
            )}
          </p>
        </div>
      </section>

      {/* Buttons */}
      <section className="section">
        <h2 className="section-title">Buttons · glass + glow</h2>
        <div className="button-row">
          <button className="btn-primary">
            <span>Primary</span>
            <span className="btn-glow" aria-hidden />
          </button>
          <button className="btn-secondary">Secondary</button>
          <button className="btn-ghost">Ghost</button>
          <button className="btn-ai">
            <span className="sparkle">✦</span>
            AI action
          </button>
          <button className="btn-secondary" onClick={() => setShowModal(true)}>
            Open glass modal
          </button>
        </div>
      </section>

      {/* Logo */}
      <section className="section">
        <h2 className="section-title">Logo · Layered M on glass</h2>
        <div className="logo-row">
          <LayeredM size={48} />
          <LayeredM size={96} />
          <LayeredM size={160} />
        </div>
        <div className="logo-row">
          <div className="logo-card">
            <Wordmark />
            <span className="caption">Wordmark · Inter on dark</span>
          </div>
        </div>
      </section>

      <footer className="footer">
        <p>v8 Variant D · Liquid Glass · Inter + backdrop-filter</p>
        <p className="caption">
          References: Apple Intelligence, visionOS, macOS Tahoe, iOS 19 Glass.
        </p>
      </footer>

      {showModal && (
        <div className="modal-backdrop" onClick={() => setShowModal(false)}>
          <div className="modal" onClick={(e) => e.stopPropagation()}>
            <h2 className="section-title" style={{ marginBottom: 12 }}>
              Save to Memory.Wiki
            </h2>
            <p className="card-body">
              This conversation will be saved to your Memory.Wiki at a fresh URL.
              Any AI can fetch it.
            </p>
            <div className="modal-actions">
              <button className="btn-ghost" onClick={() => setShowModal(false)}>
                Cancel
              </button>
              <button className="btn-primary">
                <span>Save</span>
                <span className="btn-glow" aria-hidden />
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function Swatch({ label, hex }: { label: string; hex: string }) {
  return (
    <div className="swatch">
      <div className="swatch-tile" style={{ background: hex }} />
      <div className="swatch-meta">
        <span className="swatch-label">{label}</span>
        <span className="swatch-hex">{hex}</span>
      </div>
    </div>
  );
}

function LayeredM({ size = 64 }: { size?: number }) {
  const stroke = Math.max(2, Math.round(size * 0.16));
  return (
    <svg width={size} height={size} viewBox="0 0 100 100" style={{ display: "block" }}>
      <defs>
        <linearGradient id="bgGrad" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0%" stopColor="#13131a" />
          <stop offset="100%" stopColor="#1f1f2a" />
        </linearGradient>
        <linearGradient id="mGrad" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0%" stopColor="#fb923c" />
          <stop offset="100%" stopColor="#ff6b9d" />
        </linearGradient>
      </defs>
      <rect width="100" height="100" rx={size * 0.22} fill="url(#bgGrad)" />
      <path
        d="M22 76 V 32 L 50 60 L 78 32 V 76"
        fill="none"
        stroke="#ffffff"
        strokeWidth={stroke}
        strokeLinejoin="round"
        strokeLinecap="round"
        transform="translate(4 4)"
        opacity="0.5"
      />
      <path
        d="M22 76 V 32 L 50 60 L 78 32 V 76"
        fill="none"
        stroke="url(#mGrad)"
        strokeWidth={stroke}
        strokeLinejoin="round"
        strokeLinecap="round"
      />
    </svg>
  );
}

function Wordmark() {
  return (
    <span
      style={{
        fontFamily: "var(--font-inter), -apple-system, sans-serif",
        fontSize: 34,
        fontWeight: 700,
        lineHeight: 1,
        letterSpacing: "-0.04em",
      }}
    >
      <span
        style={{
          background: "linear-gradient(135deg, #fb923c 0%, #ff6b9d 100%)",
          WebkitBackgroundClip: "text",
          WebkitTextFillColor: "transparent",
          backgroundClip: "text",
        }}
      >
        Memory
      </span>
      <span style={{ color: "#ffffff" }}>.Wiki</span>
    </span>
  );
}
