"use client";

import { useState } from "react";
import "./preview.css";

export function PreviewClient() {
  const [streamedText, setStreamedText] = useState("");
  const [showModal, setShowModal] = useState(false);
  const [activeFont, setActiveFont] = useState<"instrument" | "fraunces">("instrument");

  const fullText =
    "Your weekly digest: 12 captures this week, clustered into 3 themes. " +
    "Memory.Wiki noticed a strong connection between your TypeScript notes " +
    "and the new design system you started capturing on Thursday.";

  const startStream = () => {
    setStreamedText("");
    let i = 0;
    const interval = setInterval(() => {
      i++;
      setStreamedText(fullText.slice(0, i));
      if (i >= fullText.length) clearInterval(interval);
    }, 18);
  };

  return (
    <div className="v8-preview" data-font={activeFont}>
      {/* ─── Sticky font toggle ─── */}
      <div className="font-toggle">
        <button
          className={activeFont === "instrument" ? "is-active" : ""}
          onClick={() => setActiveFont("instrument")}
        >
          Instrument Serif
        </button>
        <button
          className={activeFont === "fraunces" ? "is-active" : ""}
          onClick={() => setActiveFont("fraunces")}
        >
          Fraunces
        </button>
      </div>

      {/* ─── Hero ─── */}
      <section className="hero">
        <div className="hero-badge">v8 visual direction — not production</div>
        <h1 className="display">
          Stop re-explaining
          <br />
          <em>your context</em> to every AI.
        </h1>
        <p className="hero-sub">
          One URL every AI fetches. Yours, your team&apos;s, or your community&apos;s.
        </p>
        <div className="cta-row">
          <button className="btn-primary">Start your Memory.Wiki</button>
          <button className="btn-ghost">See an example →</button>
        </div>
      </section>

      {/* ─── Color palette ─── */}
      <section className="section">
        <h2 className="section-title">Warm-tinted palette</h2>
        <div className="palette-grid">
          <Swatch token="--bg" label="Background" hex="#0d0b08" />
          <Swatch token="--surface" label="Surface" hex="#1a1714" />
          <Swatch token="--elevated" label="Elevated" hex="#232019" />
          <Swatch token="--text" label="Text" hex="#faf5ed" />
          <Swatch token="--muted" label="Muted" hex="#b8b0a0" />
          <Swatch token="--accent" label="Accent (brand)" hex="#fb923c" />
          <Swatch token="--ai" label="AI tint" hex="#c4b5fd" />
          <Swatch token="--border" label="Border" hex="#2d2823" />
        </div>
      </section>

      {/* ─── User vs AI vs Edited ─── */}
      <section className="section">
        <h2 className="section-title">Dual-layer cards</h2>
        <p className="section-lede">
          Original sacred · AI assistive · Edited reclaims ownership
        </p>
        <div className="card-row">
          {/* User card */}
          <div className="card card-user">
            <div className="card-meta">
              <div className="avatar">R</div>
              <span className="card-author">raymind</span>
              <span className="card-time">2h ago</span>
            </div>
            <h3 className="card-title">v8 thinking — capture vs memory</h3>
            <p className="card-body">
              Memory.Wiki이 메모리 레이어가 되려면 나에 대해서 잘 알아야 함.
              그래서 capture everything 이 자연스러운 입구.
            </p>
            <div className="card-tags">
              <span className="tag">#v8</span>
              <span className="tag">#thinking</span>
            </div>
          </div>

          {/* AI card */}
          <div className="card card-ai">
            <div className="card-meta">
              <span className="badge-ai">
                <span className="sparkle">✦</span> Generated by Claude
              </span>
              <span className="card-time">Sunday digest</span>
            </div>
            <h3 className="card-title">Weekly synthesis — 3 themes emerged</h3>
            <p className="card-body">
              You captured 12 docs this week across TypeScript patterns,
              v8 design direction, and cross-AI memory thinking. The strongest
              connection is between your design notes from Thursday and the
              v8 plan you wrote Monday.
            </p>
            <div className="card-tags">
              <span className="tag tag-ai">#digest</span>
              <span className="tag tag-ai">#synthesis</span>
            </div>
          </div>

          {/* Edited card */}
          <div className="card card-user">
            <div className="card-meta">
              <div className="avatar">R</div>
              <span className="card-author">raymind</span>
              <span className="card-footnote">
                <em>edited — originally Claude</em>
              </span>
            </div>
            <h3 className="card-title">My current focus</h3>
            <p className="card-body">
              Shipping Memory.Wiki v8 over 20 weeks. Capture → Organize →
              Use framework. Cross-AI delivery is the wedge giants cannot build.
            </p>
            <div className="card-tags">
              <span className="tag">#focus</span>
              <span className="tag">#v8</span>
            </div>
          </div>
        </div>
      </section>

      {/* ─── Streaming AI text demo ─── */}
      <section className="section">
        <h2 className="section-title">AI streaming feel</h2>
        <p className="section-lede">
          Calm purple glow during generation · char-by-char appear · settles when done
        </p>
        <div className="card card-ai streaming-demo">
          <div className="card-meta">
            <span className="badge-ai">
              <span className="sparkle">✦</span> Memory.Wiki AI
            </span>
            <button className="stream-btn" onClick={startStream}>
              Generate again
            </button>
          </div>
          <p className="card-body streaming-text">
            {streamedText || (
              <span className="streaming-prompt">Click &ldquo;Generate again&rdquo; →</span>
            )}
            {streamedText && streamedText.length < fullText.length && (
              <span className="cursor" />
            )}
          </p>
        </div>
      </section>

      {/* ─── Buttons ─── */}
      <section className="section">
        <h2 className="section-title">Buttons</h2>
        <div className="button-row">
          <button className="btn-primary">Primary action</button>
          <button className="btn-secondary">Secondary</button>
          <button className="btn-ghost">Ghost</button>
          <button className="btn-ai">
            <span className="sparkle">✦</span> AI action
          </button>
          <button className="btn-danger">Destructive</button>
        </div>
      </section>

      {/* ─── Glass modal trigger ─── */}
      <section className="section">
        <h2 className="section-title">Glass modal</h2>
        <p className="section-lede">
          backdrop-filter blur · elevated surface · breathing room
        </p>
        <button className="btn-secondary" onClick={() => setShowModal(true)}>
          Open modal
        </button>
      </section>

      {/* ─── Typography stack ─── */}
      <section className="section">
        <h2 className="section-title">Typography stack</h2>
        <div className="type-stack">
          <div className="type-row">
            <span className="type-label">Display · serif</span>
            <h1 className="display">Memory is yours.</h1>
          </div>
          <div className="type-row">
            <span className="type-label">Display · serif italic</span>
            <h1 className="display">
              <em>The graph is the product.</em>
            </h1>
          </div>
          <div className="type-row">
            <span className="type-label">Heading · sans</span>
            <h2 className="section-title">Cross-AI is the wedge</h2>
          </div>
          <div className="type-row">
            <span className="type-label">Body · sans</span>
            <p className="card-body">
              The original document stays immutable. AI metadata sits on top
              as a layer the user can lock, edit, or reject. Same source data,
              different consumers.
            </p>
          </div>
          <div className="type-row">
            <span className="type-label">Caption · sans</span>
            <p className="card-time">Captured 2026-05-23 · 12 minutes ago</p>
          </div>
        </div>
      </section>

      {/* ─── Logo symbol candidates ─── */}
      <section className="section">
        <h2 className="section-title">Logo symbol — Layered M</h2>
        <p className="section-lede">
          App icon · favicon · social. Wordmark stays for branded surfaces.
        </p>
        <div className="logo-row">
          <LayeredM size={32} />
          <LayeredM size={64} />
          <LayeredM size={128} />
          <LayeredM size={192} />
        </div>
        <div className="logo-row">
          <div className="logo-card">
            <LayeredM size={64} />
            <span className="caption">App icon</span>
          </div>
          <div className="logo-card">
            <Wordmark />
            <span className="caption">Wordmark — current</span>
          </div>
          <div className="logo-card combo">
            <LayeredM size={28} />
            <Wordmark small />
            <span className="caption">Combined</span>
          </div>
        </div>
      </section>

      <footer className="footer">
        <p>v8 preview · iterating on Memory.Wiki visual direction</p>
        <p className="caption">
          Toggle fonts at top to compare Instrument Serif vs Fraunces.
          Both are on Google Fonts and load via next/font.
        </p>
      </footer>

      {/* ─── Modal ─── */}
      {showModal && (
        <div className="modal-backdrop" onClick={() => setShowModal(false)}>
          <div className="modal" onClick={(e) => e.stopPropagation()}>
            <h2 className="section-title">Save to Memory.Wiki</h2>
            <p className="card-body">
              This conversation will be saved to your Memory.Wiki at a fresh URL.
              Any AI can fetch it.
            </p>
            <div className="modal-actions">
              <button className="btn-ghost" onClick={() => setShowModal(false)}>
                Cancel
              </button>
              <button className="btn-primary">Save</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function Swatch({ token, label, hex }: { token: string; label: string; hex: string }) {
  return (
    <div className="swatch">
      <div className="swatch-tile" style={{ background: hex }} />
      <div className="swatch-meta">
        <span className="swatch-label">{label}</span>
        <span className="swatch-hex">{hex}</span>
        <span className="swatch-token">{token}</span>
      </div>
    </div>
  );
}

function LayeredM({ size = 64 }: { size?: number }) {
  // Two overlapping M strokes — orange + warm white — at slight offset.
  // Memory's first letter, layered identity.
  const stroke = Math.max(2, Math.round(size * 0.16));
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 100 100"
      style={{ display: "block" }}
    >
      <rect width="100" height="100" rx="22" fill="#1a1714" />
      {/* Back layer — warm white, offset down-right */}
      <path
        d="M22 76 V 32 L 50 60 L 78 32 V 76"
        fill="none"
        stroke="#faf5ed"
        strokeWidth={stroke}
        strokeLinejoin="round"
        strokeLinecap="round"
        transform="translate(4 4)"
        opacity="0.55"
      />
      {/* Front layer — orange brand */}
      <path
        d="M22 76 V 32 L 50 60 L 78 32 V 76"
        fill="none"
        stroke="#fb923c"
        strokeWidth={stroke}
        strokeLinejoin="round"
        strokeLinecap="round"
      />
    </svg>
  );
}

function Wordmark({ small = false }: { small?: boolean }) {
  return (
    <span
      style={{
        fontFamily: "var(--font-active-display, var(--font-instrument-serif))",
        fontSize: small ? 22 : 32,
        fontWeight: 400,
        lineHeight: 1,
        letterSpacing: "-0.02em",
      }}
    >
      <span style={{ color: "#fb923c" }}>Memory</span>
      <span style={{ color: "#faf5ed" }}>.Wiki</span>
    </span>
  );
}
