// Generated by style-dictionary.config.mjs from design-tokens/accent-palette.json. Edit the JSON; never this file.

export type AccentColor =
  | "lime"
  | "orange"
  | "blue"
  | "purple"
  | "pink"
  | "green"
  | "teal"
  | "red"
  | "yellow"
  | "gray"
  | "sage"
  | "slate"
  | "sand"
  | "mauve"
  | "rose"
  | "iris";

export type AccentGroup = "vivid" | "muted";

export interface AccentColorOption {
  name: AccentColor;
  label: string;
  /** Color used when the doc/app is in dark mode. */
  dark: string;
  /** Color used when the doc/app is in light mode. */
  light: string;
  /** Picker group. Pickers render `vivid` first, then `muted` under a section header. */
  group: AccentGroup;
}

export const ACCENT_COLORS: AccentColorOption[] = [
  { name: "lime", label: "Lime", dark: "#B5FF1A", light: "#5BC700", group: "vivid" },
  { name: "orange", label: "Orange", dark: "#fb923c", light: "#ea580c", group: "vivid" },
  { name: "blue", label: "Blue", dark: "#60a5fa", light: "#2563eb", group: "vivid" },
  { name: "purple", label: "Purple", dark: "#a78bfa", light: "#7c3aed", group: "vivid" },
  { name: "pink", label: "Pink", dark: "#f472b6", light: "#ec4899", group: "vivid" },
  { name: "green", label: "Green", dark: "#4ade80", light: "#16a34a", group: "vivid" },
  { name: "teal", label: "Teal", dark: "#2dd4bf", light: "#0d9488", group: "vivid" },
  { name: "red", label: "Red", dark: "#f87171", light: "#dc2626", group: "vivid" },
  { name: "yellow", label: "Yellow", dark: "#fbbf24", light: "#d97706", group: "vivid" },
  { name: "gray", label: "Gray", dark: "#a1a1aa", light: "#52525b", group: "vivid" },
  { name: "sage", label: "Sage", dark: "#94B49F", light: "#5E8669", group: "muted" },
  { name: "slate", label: "Slate", dark: "#7C8DA8", light: "#536175", group: "muted" },
  { name: "sand", label: "Sand", dark: "#C7B299", light: "#8C7656", group: "muted" },
  { name: "mauve", label: "Mauve", dark: "#B193A6", light: "#7B5E72", group: "muted" },
  { name: "rose", label: "Rose", dark: "#C99595", light: "#965C5C", group: "muted" },
  { name: "iris", label: "Iris", dark: "#7E7FB0", light: "#52537A", group: "muted" },
];

/** Whitelist of every accent key any client can persist. The server
 *  PATCH /api/user/profile handler uses this to validate the
 *  accent_color field — native clients (iOS/Android/Desktop/VSCode/
 *  CLI) hit that endpoint over bearer auth, so anything not in this
 *  set 400s and the client's runCatching silently swallows. Keeping
 *  it derived from ACCENT_COLORS guarantees: add an item to the
 *  JSON, the server accepts it on the next build. */
export const ACCENT_KEYS: ReadonlySet<string> = new Set<string>(["lime", "orange", "blue", "purple", "pink", "green", "teal", "red", "yellow", "gray", "sage", "slate", "sand", "mauve", "rose", "iris"]);
